### ISSUE TITLE
Open in New Window menu item not appearing in Office 365

### ISSUE THREAD

**Issue by atrasatti** [wavebox/waveboxapp#1074]
* Wavebox Version: 4.10.5
* Operating System & Version: Mac OSX 10.14.5
* Account type (if applicable): Office 365

**Expected & actual behavior**
Right click on the service icon on the left toolbar opens a menu, the first two items should be about opening a new window and a new window in this service. For some reason my Office 365 icon doesn't let me do it. Strangely I have Office's calendar as a sub-service icon on the left and there I do see the open new window entry. See screenshot below.

**Steps to reproduce**
I have office 365 setup as my first service, so listed as first icon on the left. I have Outlook as the default (not sure if these make any difference). I right click and a menu opens. Open new window is not listed.

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
Two screenshots here, one when right clicking on the main service icon and one when clicking on the secondary icon which is calendar for me.

**Additional information**
I have 8 other service icons on the left and right clicking on any of them shows the "open in new window" and "in this service" menu items.

![Right-click on Office 365 service icon](https://user-images.githubusercontent.com/332952/62486128-4481f380-b773-11e9-9124-15a697720390.png)

![Right-click on calendar icon inside Office 365](https://user-images.githubusercontent.com/332952/62486152-5499d300-b773-11e9-81af-f06dc7eade4e.png)

**Comment by Thomas101** [comment]
It's because the larger icon produces a menu for the group (which includes all 10 services/tabs), whereas the smaller one is for the individual tab - hence why they're slightly different.

The UX could be a little bit skewed if you've changed the `Service Prioritization` setting under account settings. Changing this from normal still has some rough edges. I couldn't quite figure out if you'd changed it from the screenshots though...

![Screenshot 2019-08-06 at 09 15 09](https://user-images.githubusercontent.com/103586/62523073-ec0e2d00-b82a-11e9-887e-9f2c91051bf5.png)

... would be good to know more about your setup here

**Comment by atrasatti** [comment]
> It's because the larger icon produces a menu for the group (which includes all 10 services/tabs), whereas the smaller one is for the individual tab - hence why they're slightly different.

I see, in fact the service icon for Gsuite does the same. I think as a user it's confusing and I don't know why for the main icon for a collection of services I would not need the "open in new window" item.

> ... would be good to know more about your setup here

I checked and it's the same as your screenshot, "Normal".

**Comment by Thomas101** [comment]
> I think as a user it's confusing and I don't know why for the main icon for a collection of services I would not need the "open in new window" item.

Yep, I agree. This has just gone out in 4.11.1
