### ISSUE TITLE
Inbox & Gmail

### ISSUE THREAD

**Issue by rawkode** [wavebox/waveboxapp#115]
I often switch between Inbox and Gmail: can I have the ability to add a Google account, rather than specifying between the two; and the ability to switch through the app switcher?

* Which version of Wavebox are you using? [e.g. 3.0.0]

3.1.5

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Linux - Arch

**Comment by Thomas101** [comment]
Hi, you can add the same account twice and add one as Google Inbox and the other as Gmail. You will get duplicate notifications and unread counts, but you can disable them for one of the accounts depending how you want to set this up. Would that work for what you're trying to do?

**Comment by rawkode** [comment]
@Thomas101 Is there a reason you make us choose?

My normal flow is to use Inbox, but when I need to search for emails, I tend to jump back to Gmail.

I don't know why you'd suggest adding two accounts, when it's the same account, but a different URL? Why is Inbox and Gmail not a selectable service, like Keep, on the switcher? :smile:

**Comment by Thomas101** [comment]
There isn't any specific reason, there was just an assumption that most users would only access email through one method or the other.

In addition to this, because unread notifications and counts are handled differently between Gmail and Google Inbox we didn't want to try and confuse the fact that Gmail may display 10 messages using important & unread ranking whereas Inbox may display a different count as it may have grouped items together in bundles for example.

It's certainly possible to add in, I'll need to look at what implications this has under the hood though as gmail and inbox sit within the same service category on the same account

**Comment by Thomas101** [comment]
Hi, we're collapsing all the new Google Service requests into a single issue so we can keep track of them more closely. You can find and continue tracking progress from #131. Thanks!
