### ISSUE TITLE
Youtube video disappears when hover over sidebar

### ISSUE THREAD

**Issue by VarunAgw** [wavebox/waveboxapp#1156]
* Wavebox Version: [e.g. 3.0.0] Wavebox Latest Beta
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10] Windows 1909

1. Play a video on youtube.
2. Hover mouse over sidebar for few seconds until you see the Pinned/Recent popup.

Youtube video will disappear and you will see the white background instead. Sound will keep working.

Hovering mouse back to video fixes it.

**Comment by Thomas101** [comment]
Thanks, I've managed to reproduce it here, I'll see if we can get it fixed

**Comment by Thomas101** [comment]
Just an update on this. We think we might have found the root cause as well a workaround. We should be shipping the fix with the next beta.

If you want to use work around here's how...
* Open a new tab and navigate to chrome://flags
* Look for the "occlusion of web contents" and change it from default, to be disabled and restart Wavebox

There may be a slight performance hit from doing this especially on heavy websites, however the next beta should fix this properly :)

**Comment by VarunAgw** [comment]
Thanks, @Thomas101. It's pretty low priority for me. Just thought I should report it to help make the Software better.

**Comment by VarunAgw** [comment]
Thanks.
