### ISSUE TITLE
MS teams notification - does not open conversation on click

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#1159]
* Wavebox Version: 10.0.35
* Operating System & Version: windows 10
* Account type (if applicable): MS teams

**Expected & actual behavior**
Open conversation on click of notification.

Does nothing more then close the notification. Nothing happens.

**Steps to reproduce**
Click on any notification on popup or even in notification area of windows 10.

**Is the bug persistent or intermittent?**
Persistent

**Additional information**
wavebox does not even get focus or anything. Not sure what is going on.

**Comment by Thomas101** [comment]
Sorry for the delay - is this a notification that's just popped up or one that's been in the action centre for a while?

**Comment by nmat** [comment]
I tested with both new and old notifications, seems to be the same.

The popup now however seems to work its only for the action center.

Win version: 1903 (OS Build 18362.535)

**Comment by Thomas101** [comment]
I think I've found what this is! There are few quirks with Windows notifications. Notifications in windows have this flow...

1. Open a notification
    * You can voluntarily call close to get rid of the notification
    * You get click events
2. After a few seconds, it goes into the action centre
    * It fires the "close" event
    * The creator can no longer voluntarily close the notification
    * You continue getting click events

Teams knows this and does the following...

1. Open notification
2. On show event, setTimeout
3. Close notification

This gives the effect of it appearing but not going into the action centre.

The bug was there's a race condition in Wavebox, which meant sometimes it would sometimes get "closed" into the action centre before teams called close on it. This meant you had an orphaned notification that was unclickable :).

10.0.47 has a fix for this :)
