### ISSUE TITLE
Message Delivered to Wrong Window

### ISSUE THREAD

**Issue by rawkode** [wavebox/waveboxapp#116]
This has now happened a few times, at-first I thought it was me being daft; but it's definitely a problem with Wavebox. However, I don't know how to re-produce.

Typing message into a window results in a message being posted into a different window.

Example: Typing in a Slack channel, message delivered to a HipChat session instead.

I'm sure this is some focus bug and I've not been paying attention to the text input box, but this is a pretty serious flaw. Hopefully you are able to reproduce and fix :+1: 

* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.5

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Linux - Arch

**Comment by Thomas101** [comment]
Did you see the text appearing in the slack channel where you were meant to be typing? How do you normally switch accounts, is it by clicking the the accounts in the sidebar or using a keyboard shortcut? Thanks

**Comment by rawkode** [comment]
I'm paying more attention to what I'm doing and hoping to reproduce.

I always click on the icons, I rarely use <kbd>Control</kbd>+<kbd><Num></kbd>

**Comment by Thomas101** [comment]
Thanks!

**Comment by Thomas101** [comment]
Hi, I've been looking into this a bit more and I think it may have been down to an issue where Wavebox didn't refocus the correct mailbox when switching back to it using <kbd>Alt</kbd>+<kbd>Tab</kbd>. In this instance you could find yourself typing into incorrect account unknowingly. 

This focus bug was fixed in 3.1.6 and I'm guessing because you haven't re-commented you haven't seen again. I'm going to close this off for now, but if it does happen again feel free to message and I'll take another look.

On a side note to this, 3.1.8 has just been released :-). Thanks!

**Comment by rawkode** [comment]
Hi @Thomas101,

This bug happened quite a few times and I had to stop using, but I wasn't able to successfully reproduce it on demand, so I couldn't comment.

I've installed the latest release and I'm hoping we're all good. Thank you for finding the fixing the bug
