### ISSUE TITLE
Youtube: Couldn't sign you in

### ISSUE THREAD

**Issue by tjventurini** [wavebox/waveboxapp#1174]
* Wavebox Version: wavebox_10.0.42-1_amd64.deb
* Operating System & Version: Ubuntu 18.04
* Install method: Debian installer
* Account type (if applicable): Youtube/Google

**Expected & actual behavior**
When I try to sign in to youtube I expect it to work :wink: 

But after I enter my password, I get the message

```
Couldn't sign you in
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.
```

**Steps to reproduce**
Try to sign in on youtube. In some cases, you will end up like me not being able to. I just get the message 

```
Couldn't sign you in
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.
```

**Is the bug persistent or intermittent?**
It is only happening on my notebook. Works fine at work and on my pc.

**Comment by Thomas101** [comment]
Thanks for reporting. If you give it another try does it work?

If not, do you have any extensions installed and are you able to sign in using another browser on the same pc?

**Comment by tjventurini** [comment]
Just tried it again today after the update and its working now. Thank you!

**Comment by nitaaikumar** [comment]
@Thomas101, I am facing the same problem. I did a hard refresh. I delete the Youtube app, restarted Wavebox and tried again. Then I deleted the app, restarted Mac and tried again, same error. Earlier it was not letting me add my first Youtube app. Then I restarted Wavebox and it let me add 2 youtube apps. But now it is not letting me add a third youtube app, no matter what I try as I had described above. Please provide a fix. I renewed Wavebox primarily because of managing multiple Youtube accounts. Mac OS 10.15.2, Wavebox 4.11.12 (beta) dmg.

**Comment by nitaaikumar** [comment]
Ok @Thomas101, I have upgraded to Wavebox 10.0.56.3 beta and this Youtube login error has not occured yet. But now I am facing a different problem. it is keeping the same youtube login for any new youtube app I add. So if I set another youtube channel in a new app as the default, it is making it the same in the earlier added app also. Maybe I am doing something wrong. There seems to be a learning curve for this version 10 with a lot of new features, which I don't have the time to study right now. Can you please tell me how I can make totally different youtube apps which do not modify the previous ones?
