### ISSUE TITLE
Unable to copy content from wavebox and paste to another application.

### ISSUE THREAD

**Issue by jjegg** [wavebox/waveboxapp#124]
3.1.5 on MacOS

Unable to copy content from wavebox to a 3rd party application. IE. Copy an email in gmail and paste in chrome.

**Comment by MichaelTunnell** [comment]
I just tried this and it works fine for me in 3.1.5 on KDE Neon (Ubuntu 16.04 - Linux).

I was able to successfully copy and paste via mouse/context menu as well as using Ctrl+C & Ctrl+V.

I tested this via Wavebox Account to Wavebox Account as well as Wavebox to Chrome (and Firefox).

**Comment by Thomas101** [comment]
Thanks both!

@jjegg which method are you using to copy (cmd+c, right click copy etc)? Is it just plain email text that you're trying to copy?

**Comment by Thomas101** [comment]
Going to close this off for now due to inactivity, but if you're still seeing the problem re-comment and I'll take another look. Thanks

**Comment by closerlee** [comment]
Same. Can't copy paste on Mac. Used CMD+C. Try coping from gmail to google docs with no luck. Can't copy from outside and paste in, can't copy from inside and paste out. Neither works.

**Comment by jjegg** [comment]
For me it now works, unsure what has changed..

**Comment by closerlee** [comment]
If I right click and copy out of Wavebox, it works. The keyboard shortcut
does not.

**Comment by Thomas101** [comment]
@closerlee have you changed any of the keyboard shortcuts under advanced? If you try restarting Wavebox does the behaviour change?

**Comment by closerlee** [comment]
I have not changed any of the keyboard shortcuts.

Using Wavebox at my office, copy and paste works fine. On my personal
computer it does not. Very odd.

**Comment by Thomas101** [comment]
@closerlee which types of accounts have you added into Wavebox? (e.g. one gmail, two outlook etc...)

**Comment by jlhjlh** [comment]
One gmail, one Google keep, one Trello, and one Jira.

**Comment by Thomas101** [comment]
@jlhjlh do you know which version of macOS you're using on the working machine and not-working machine?

**Comment by jlhjlh** [comment]
10.12.5 (16F73)

**Comment by Thomas101** [comment]
Version 3.1.11 has just been released, this includes an update to electron & chromium. Would you be able to see if this has the same problem? Thanks

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks

**Comment by andyunleashed** [comment]
Hi, this issue is occurring for me on OSX 10.13.3 - with Wavebox 3.10.0.

CMD+C does not work - have checked the Keyboard shortcuts section and nothing overridden or changed from defaults. Have tried reboot/restart but no luck unfortunately.

Weirdly when I do CMD+C it does the usual flash highlight of "Edit" in the menu bar which would normally indicate that the highlighted item has been copied, but then going to paste in another app or Wavebox it doesn't paste anything.

This happens across services, Google Inbox, Basecamp, Slack so it's not service related I believe.

**Comment by andyunleashed** [comment]
Have just restarted Wavebox a couple of times and now it works again - super weird.

**Comment by Thomas101** [comment]
@andyunleashed thanks for reporting. There's definitely something here - we've seen it on a test box ourselves. As for reproducing, we're a little stumped.

Going to re-open then so we can keep an eye on it. Hopefully, if we get some more reports and use-cases we can find a path to reproduce and fix.

**Comment by andyunleashed** [comment]
I'll let you know if it returns. Seems to work fine on iMac but my 2017 MacBook seems to happen from time to time. Is there anything I can do to nail it down for you?

**Comment by Thomas101** [comment]
Until we have a better idea of where the issue lies the more info the better really. In particular...
* Which site you're on at the time?
* Which text are you trying to copy? (e.g. the text I've written in a textbox, the main body of the page)
* Does <kbd>Cmd</kbd>+<kbd>C</kbd> work?
* Does Edit > Copy work?
* Does right click copy work?
* Does trying it somewhere else work?
* How long has Wavebox been running?
* Which other apps are running? (Include those in the tray, e.g. Google Drive Sync etc....)

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks

**Comment by jesseforrest** [comment]
I'm noticing the same issue.
- MacOS Mojave 10.14
- Wavebox 4.5.3

At this point you should probably not close it out without resolving. ;)

**Comment by jesseforrest** [comment]
Your questions:

Which site you're on at the time?
  - Clubhouse
Which text are you trying to copy? (e.g. the text I've written in a textbox, the main body of the page)
   - Textbox
Does Cmd+C work?
   - No
Does Edit > Copy work?
   - No
Does right click copy work?
   - Yes
Does trying it somewhere else work?
   - Assuming you mean another application? If so, yes.
How long has Wavebox been running?
   - A couple days
Which other apps are running? (Include those in the tray, e.g. Google Drive Sync etc....)
   - Excel
   - IntelliJ
   - Virtualbox
   - DataGrip
    - Spotify
    - Dropbox
    - Google Drive
