### ISSUE TITLE
Keyboard shortcut issues

### ISSUE THREAD

**Issue by max-sixty** [wavebox/waveboxapp#1250]
- When using "Switch to the next group in current group", this will skip over any groups that are sleeping. Is it possible to instead wake up the group?
- When setting a shortcut of <Cmd+Option+Right> for "Switch to the next group in current group", the shortcut doesn't display on the first try, does display on the second, and then doesn't display when closing and reopening (but does seem to work).
- Is it possible to have <Ctrl+Tab> be for toggling to the previously selected app? IIRC that used to be an option with the older version of wavebox

Thank you!

* Wavebox Version: Version 10.0.179.2 stable
* Operating System & Version: MacOS

**Comment by Thomas101** [comment]
1. Do you mean `Switch to the next group` or `Switch to the next app in the current group` - these should both wake the apps/groups as they move along. The only one that I'm aware of that doesn't, is <kbd>Ctrl</kbd>+<kbd>Tab</kbd> and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Tab</kbd> as these cycle through the running tabs
2. Thanks I'll take a look into this one!
3. <kbd>Ctrl</kbd>+<kbd>Tab</kbd> is mapped by the underlying Chromium to toggle between tabs. We did try to overwrite this so that it could be customized, but it tended to cause more sporadic problems. I will have a look to see if this is something we can add back in - although it will probably have to be on a different keyboard combo

**Comment by max-sixty** [comment]
1. I'm pretty sure that's what's happening. I'm using `Switch to the next app in the current group`, though it seems to also change groups once it reaches the end of the group. Maybe this is related to (2)? I don't see any shortcuts listed, but <Cmd+Option+Right> seems to work to at least move through active apps.

<img width="658" alt="image" src="https://user-images.githubusercontent.com/5635139/85154702-a3761d00-b20c-11ea-9926-3f475a8d90f0.png">

Here's a `.mov` of the transition for confirmation, even if not in the ideal format 
[Wavebox.mov.gz](https://github.com/wavebox/waveboxapp/files/4805640/Wavebox.mov.gz)

3. Thanks. It was particularly nice to swap back & forth between two apps; which happens more & more now I have so much in Wavebox!

**Comment by Thomas101** [comment]
1.)  I think it's because Cmd+Option+Left/Right are mapped by chromium to cycle through active tabs. So from the settings screen, when you try to set it, it doesn't actually let you map it, but the behaviour is almost identical to what you expect it to be. If for example, you map Ctrl+Shift+Right, you should see a different behaviour




3.)  I've added this in, so it should be in the next release

**Comment by max-sixty** [comment]
Ah! That's exactly right on (1), thanks! Changing it to something else makes it work.

Thanks! I think we can close this now?
