### ISSUE TITLE
Turn off "Time to Update"

### ISSUE THREAD

**Issue by cdeutsch** [wavebox/waveboxapp#1287]
Wavebox Classic is now showing this message multiple times a day.

![image](https://user-images.githubusercontent.com/404765/100678507-f06d2c00-3332-11eb-8314-deee2b18640c.png)

I can handle once a day or on launch, but not multiple times a day. Can it be turned off?

I've tried Wavebox 10 twice now; once at launch and again today. There's just no reason for me to update to it. I'll continue to pay for Pro if you just remove that message. Otherwise I'll probably find another wrapper for Gmail which is all I really want.

Wavebox Version: [e.g. 4.11.11]
Operating System & Version: [Mac OSX 10.14.6]

**Comment by Thomas101** [comment]
Google is dropping sign-in support for Electron apps in 2021, which will impact Classic - hence the recent push to ensure everyone migrates over to Wavebox 10 ( which will continue to be supported since it's built directly on Chromium and not Electron). 

This is something that we believe will impact all Electron apps, e.g. https://github.com/meetfranz/franz/issues/1573#issuecomment-729552152

If you want to suppress the message permanently, please drop Wavebox support a message with your account details and we can disable it (but be aware of the upcoming Google change in 2021).

**Comment by cdeutsch** [comment]
That Google change is unfortunate. That makes sense. Thanks for the explanation.
