### ISSUE TITLE
don't change app icon when navigating away from homepage

### ISSUE THREAD

**Issue by rdsignr** [wavebox/waveboxapp#1288]
* Wavebox Version: [e.g. 4.0.0]
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.15.0, Ubuntu]
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...]

**Comment by mmhasse** [comment]
**Issue**: If I navigate away from an app's homepage (by clicking a link on that page or by entering a URL in the address bar), the app icon changes or goes blank. This makes it hard to find the app in the toolbar later.

**Desired behavior**: the app icon should be strictly associated with the app's url as defined in the app settings.

**Note**: This only seems to affect apps that were created with "Add any website...".

**Comment by Thomas101** [comment]
This is because we automatically grab the favicon and color from the site that you're visiting, rather than using a standard icon for all any website apps.

If there's a specific icon or color that you want to use for the app, then you can set this by right-clicking on the app in the sidebar/toolbar and going to Settings > App Settings and picking an icon on disk. Once you've done this it will stay the same

**Comment by mmhasse** [comment]
Hi Thomas,

Thanks for your reply. I understand the technical reason, but I still find
it to be bad user design a) because it hampers usability and b) because it
is inconsistent with the predefined apps' behavior. It should be
technically feasible to download the favicon once and then leave it
unchanged unless the user changes the URL in settings.

Thanks,
MH

**Comment by rdsignr** [comment]
Closing this issue as there is now an app setting under Appearance allowing the user to permantently "use current icon".
