### ISSUE TITLE
[Feature request] Hide some spaces on the webdock

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1462]
* Wavebox Version: 10.125.8-3 beta
* Operating System & Version: Fedora Workstation 40

### Feature description

Use case &sharp;1 I have a space which has only an app. I do not want it is listed always.

Use case &sharp;2 My company has a number of AWS accounts, so I used to use multiple spaces (containers) to deal with multiple logged-in AWS accounts at the same time.

![image](https://github.com/wavebox/waveboxapp/assets/28209361/f119c44a-2f77-488b-91f7-8bde7026ec62)

So the number of my spaces is more than 5 (dev, staging, production, etc.). But I am not using the entire spaces in my daily life. Therefore, it is not needed to be shown on the left sidebar.

**Comment by Thomas101** [comment]
When we were building the Spaces webdock, we did look at using an overflow menu, but the feedback we had on this was terrible because users kept losing spaces. We don't want to create a point of confusion on this, where a large segment of the app becomes unavailable/hidden - people naturally forget they've hidden stuff over time and then just get really confused!

**Comment by lens0021** [comment]
I see, I will find other solution for my case, thank you!
