### ISSUE TITLE
[Feature Request] HEX mode for badge color picker 

### ISSUE THREAD

**Issue by Stanzilla** [wavebox/waveboxapp#159]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.6
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Win 8.1

So currently `Account Color` has a HEX input box for the color, yet `Account Badge Color` has not, would be nice to have it there, too.

**Comment by Thomas101** [comment]
Hi, this is because the Account badge has opacity by default and css-hex values don't support opacity. If you drag the opacity bar all the way up (1) so there's no transparency you can then use the picker to switch back to hex (2).

![screen shot 2017-05-05 at 09 11 53](https://cloud.githubusercontent.com/assets/103586/25738091/16c04844-3173-11e7-82ee-596fef182d8f.png)
