### ISSUE TITLE
WMail Release Files Deleted

### ISSUE THREAD

**Issue by jadenPete** [wavebox/waveboxapp#17]
I noticed that you deleted the deb files for WMail? Why?

**Comment by WillPresley** [comment]
Also took down build instructions before that. Anything to push people to the new, crippled free-tier of this new crap, eh? I have no interest in using Wavebox for Slack, Trello, etc etc. But I have THREE Google accounts that I LOVED using Wmail with. One uses Inbox, Calendar, Contacts, and Keep, one is just Gmail, and the last is Gmail, Calendar, and Contacts. I will never, ever pay $20 a year to basically just unlock one additional Google account, when you are choosing to rip it out of the free product thousands of people have come to depend on. Very glad I pulled down the source and build directions while I still could, and fairly disappointed with everything that is happening. Wavebox is basically just Shift! (which I ridiculed as a crappy "paid fork" of the superior Wmail).

**Comment by andyunleashed** [comment]
@WillPresley I don't think that's particularly fair on them. Sure maybe they shouldn't have removed the existing app source, but is $20 seriously a big deal when they've clearly put a boat load of work into it, and provided a free product for so long? I've already bought the new app because it's great and I want to support their endeavour.

**Comment by WillPresley** [comment]
@andyunleashed Yes, I do think that pulling existing features out of an open-source and/or free project in order to have marketable "premium" features is a big deal. Using the 2.3.X release of Wmail as the base for Wavebox would not have irked me in the least, and I probably would have paid the yearly price, even though I have no desire to use Slack or Trello inside of it (I prefer using them separately). Instead the existing product was purposely crippled in order to provide ANY value for the new (and unnecessary) premium offering, and then any options for downloading/building/etc the old, open-source project were ALSO removed. BTW, the open source project had LOTS of contributors that were not the person who is now making money (or making money for their company) with this. The whole thing screams "money grab" to me, honestly, and like I said it's just super disappointing.. I will move on painlessly.

**Comment by andyunleashed** [comment]
@WillPresley As far as I can see everything is still there in the releases no?
 https://github.com/Thomas101/wmail/releases

Further, in terms of contributors I think it's pretty obvious that Thomas has been the one doing the vast majority for a long time: https://github.com/Thomas101/wmail/graphs/contributors

I get that you're upset but you seem pretty vitriolic about someone trying to make a bit of cash for their work. Why is it a bad thing for people to get paid for their work?

**Comment by WillPresley** [comment]
Tags are there, downloads most certainly are not. In terms of contributors, sure, that may be the case that most commits have come from them. And lastly.. I am not vitriolic at all. I am a professional web and mobile developer, and I VERY MUCH understand that a developer would want to make money after putting this much time into a project like this. Like I explained very clearly in my last reply, HOW this change has been made, and WHAT was chosen to move to the "paid" tier are what upsets me.

**Comment by Thomas101** [comment]
We only want to make the current binaries available to help with ongoing support - which are now found in this repo. The source is always there (with full git history of course).

We’re completely committed to open-source, with Wavebox free as in free speech, not free as in free beer. i.e. you can always have access to the code for your client and you can either spend some time to build it yourself/contribute some code, or buy the pro version and let us continue supporting the project.

**Comment by MichaelTunnell** [comment]
@Thomas101, 

I have absolutely no problem with software trying to make money off their efforts. I think more and more open source projects should provide a commercial option but the way you went about it was a mistake.

You changed the branding and the offering abruptly with no notice for users. I didn't even know about it until today when I was talking to someone I had convinced to switch to WMail a few weeks ago and they told me "haven't you heard, WMail new version went premium only?".

Simply creating a premium version wouldn't bother me but an arbitrary limit of 2 accounts was made for "free users". For software that relies on a multi-account structure, two accounts is literally the absolute minimum you could have chosen and still be technically "multi-account". This arbitrary restriction just tells all your previous users "thanks for making my project popular but now I want your money".

**I am not bothered by the price at all. $20 per year is a very reasonable price BUT here's problem:**
1. you didn't tell your users it was happening until after
2. you've removed the ability for users to choose to keep WMail (without compiling or unless they already had it)
3. you've set an account limit that essentially makes the free version useless.
4. you've essentially made it where long term users like myself are thinking "what about next time?" "When you pull the rug out from under me next time, how bad will it be then?"
5. I contributed to this project in advocacy, bug hunting, pre-release testing and code commits . . . because of the above, this abrupt and restrictive change just tells me "thanks but give me money if you want the new features or bug fixes".

**It's not too late though:**
Out of the 5 complaints I listed above, only 1 significantly bothers me . . . **(3)**

**Here's what you could do to fix it, for me:
1. Increase the account limit to 10 or at the minimum of 5.**

Seriously, that's really all that is needed.

Potential response to my suggestion:
"Michael, I get it. You want a minimum of 5 because you have 4 accounts. Try to be less transparent."

Actually, I have 4 google accounts that I need, not 4 that I want. I have roughly 8 that I would like to use but I chose not to use 8 via WMail because it didn't have account sleep when inactive (idea I requested months ago that suddenly appears in the Pro-only Wavebox). I didn't want 1GB of my RAM being used on email.

Additionally, I have 2 Trello, 2 Slack, and at least 5 custom app accounts that I would create so for me, the limit of 10 is not enough. I'd have 17 accounts so I'd certainly be in the Pro tier.

------

The thing that bothers me is not that you want money, I wish nothing but the best for you and this project but the fact that **you did not ask for donations on WMail** at all yet this abrupt change happens with money seemingly being the primary factor. I did all of the other stuff you asked for like: Bug Hunting, Code Contributions, Pre-Release Testing, and so on. I did all of that and I would have donated money to the project as well had you ever asked for it.

Again asking for money now isn't the problem . . . it's the arbitrary restriction that turns the "request for money" into a *requirement* of money to even use the software at any reasonable level.

Wavebox is now competing with Franz, Rambox, etc. and I need more than 2 accounts to test if it's worth my time to pay for it.

------

If the Wavebox model was used on WMail at inception, I never would have made this comment because I never would have even tried it out of principal of "multi-account software restricting to 2 accounts". I wonder how many people will miss out on Wavebox's potential simply because of this weird restriction convinces them not to bother.

**Comment by WillPresley** [comment]
@MichaelTunnell You just said every single thing that I have to say, except better and with more detail. Thank you for breaking down, logically, why this ENTIRE situation is a huge kick in the teeth to longtime users.

Personally? I'm already happily modifying my fork of 2.3.1, and keeping an eye out for either a change in pricing structure or an alternative (true) open source project.

**Comment by MichaelTunnell** [comment]
> You just said every single thing that I have to say, except better and with more detail. Thank you for breaking down, logically . . .

Welcome. :)

> this ENTIRE situation is a huge kick in the teeth to longtime users

I am very much annoyed by this situation but I'd describe it less like "kick in the teeth" and more like "those people who refuse to be courteous on a crowded street that instead of twisting their upper body to get past other people politely they just walk firm and shove their shoulder into you as if saying 'it's my street punk, get out of my way'."

Yea, more like that. :)

> I'm already happily modifying my fork of 2.3.1, and keeping an eye out for either a change in pricing structure or an alternative (true) open source project.

I understand that approach. I don't need the pricing to change just the account limit to be reasonable and not absurdly restrictive.

> an alternative (true) open source project

To be fair about the Open Source part, this project is truly Open Source already even with this restriction.

Open Source does not require gratis to fit, only the source code being freely available and modifiable which it is.

Wavebox (and WMail) uses MPL and this license permits everything they are doing and is considered an Open Source license. It's not technically considered "Free Software" license but what they are doing is permissible to licenses that are like the GPL. For example, the GPL doesn't require binaries be provided, only source code which they have complied with that.

If the source code provided has proprietary blobs somewhere for the account restriction, they that would be a violation of both licenses but I am unaware of any such blobs.

**Comment by WillPresley** [comment]
I should have clarified that last part you quoted. Wmail was a proper open-source project, and I quickly was able to get 2.3.1 to build locally. Wavebox, however, includes this somewhat strange Google Form they are calling a "custom build configuration", which requires an email address and GitHub username, presumably to do exactly what you just mentioned... utilize proprietary blobs/tokens/salts/etc, so as not to "affect" their Pro sales.

To be fair, I am not filling out that form, nor am I buying into any of this Wavebox nonsense, due to the reasons you described, so I am not 100% sure of what that "custom build configuration" actually entails. With the choices being made recently though, it wouldn't surprise me at all if that is exactly what that little line is there for.

**Comment by MichaelTunnell** [comment]
> Wavebox, however, includes this somewhat strange Google Form they are calling a "custom build configuration" (see: https://github.com/wavebox/waveboxapp#building-wavebox), which requires an email address and GitHub username, presumably to do exactly what you just mentioned... utilize proprietary blobs/tokens/salts/etc, so as not to "affect" their Pro sales.

I did not see that previously . . . yea that's not very comforting at all. Thanks for clarifying.

**Comment by jadenPete** [comment]
Can someone please make a fork of Wavebox and remove this crap?

**Comment by jadenPete** [comment]
What really aggravates me is the deleted build instructions.

**Comment by pkajaba** [comment]
Instructions can be found in git history of wiki and even packager scripts are in history. It takes around 5 minutes of effort to build it for yourself even now

**Comment by nonamethanks** [comment]
Want to see proof that this is only a half-assed money grabbing scheme? Look no further than the fact that Google Drive and other services (which were implemented FOR FREE in Wmail) are now behind a paywall. 
What a fucking scam.

**Comment by sha1** [comment]
Man, all this bitching and whining for 20 bucks? What a bunch of retards.

**Comment by MichaelTunnell** [comment]
> Look no further than the fact that Google Drive and other services (which were implemented FOR FREE in Wmail) are now behind a paywall.

I don't recall WMail offering Drive or other services at all.

> Man, all this bitching and whining for 20 bucks? What a bunch of retards.

Try to be less of a prick. As for the price, that's not an issue. I am fine with it and am in fact a paid subscriber of Wavebox but it still bothers me they made these changes with no warning at all and removed build instructions for the older version of the software.

That doesn't change whether or not Wavebox is worth paying for, and I think it is but that also doesn't change my opinion as to whether or not the actions made during the transition were irritating.

The money is not what people were complaining about.

**Comment by nonamethanks** [comment]
>I don't recall WMail offering Drive or other services at all.
https://github.com/Thomas101/wmail/search?utf8=%E2%9C%93&q=drive&type=

**Comment by Thomas101** [comment]
I don't think this is a technical issue anymore.
