### ISSUE TITLE
Why do I need an "API Key" to build this?

### ISSUE THREAD

**Issue by cmoro-deusto** [wavebox/waveboxapp#174]
Hi

pretty much the title says it all. I'm grateful that you released this as open source, but I find the "API Key" thingy a wee bit strange... Here you have some questions, that maybe you are kind enough to answer.

- Why do I need to download another application, fill up a form with my info in order to get an "API Key" so I can build this? 
- What's that API Key used for during building and afterwards, when I use the compiled application?
- Is it used to tie my personal info (the one entered to get the "API Key") with some kind of telemetry/app usage patterns?

Thanks very much!

* Which version of Wavebox are you using? [e.g. 3.0.0]
None yet, need answers to questions.
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
All of the above and more. You name it.

**Comment by Thomas101** [comment]
Hi, I agree that downloading the pre-build version of Wavebox to get your API key is a bit backwards. This is purely because it’s been super-hectic our end and this was the easiest thing to do at the time. We do plan on moving this onto the web at some point in the future. We’ve gone down the the API key route since it fits better with the work that’s underway around extensions & extra services including those that we will be hosting ourselves over the next few months.

**Comment by cmoro-deusto** [comment]
Thanks for your reply. 

Would not be more logical to just add a setting in the app to enter the API Key whenever it is (and if) needed in the future to use those services? I don't see the real (technical) need to get an API Key to compile an open source project.
