### ISSUE TITLE
Using too much memory

### ISSUE THREAD

**Issue by OrhanOdabasi** [wavebox/waveboxapp#186]
It's using so much memory to a small app like this. About 350MB is allocated.

* Which version of Wavebox are you using? [e.g. 3.0.0]
Wavebox version 3.1.7
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Elementary OS 4.4.0

**Comment by Thomas101** [comment]
Hi, have you tried sleeping the tabs that you use less frequently? This can save huge amounts of memory. https://blog.wavebox.io/put-wavebox-sleeping-tabs-to-the-test/

**Comment by OrhanOdabasi** [comment]
Single account and two services are active. Sleeping is enabled but still using significant amount of  memory. At least I expect from this app to use much less memory than it does right now.

**Comment by MichaelTunnell** [comment]
> It's using so much memory to a small app like this. About 350MB is allocated.

Wavebox is an Electron app . . . this is normal for Electron apps that do as much as Wavebox does. My current Wavebox setup is 280MB with sleep mode enabled on all of my accounts. I have 7 accounts right now and plan to add more because the sleep mode is perfect to solve this issue.

> At least I expect from this app to use much less memory than it does right now.

You shouldn't expect that because Electron apps are bundled with their own version of Chromium. The issue is that every account you add essentially adds another Chromium tab and Chromium is the most bloated browser ever made. Unfortunately, it's the only option for the Electron team to use because Firefox is a mess right now. In my opinion, the sleep mode is a critical feature.

--------

unrelated but elementaryOS is on version 0.4 not 4.4.0 as that I assume is your kernel version but is not really relevant to give people in terms of distro version.

**Comment by OrhanOdabasi** [comment]
My bad, sorry. Elementary OS 0.4.1 Kernel 4.4.0 based on Ubuntu 16.04. If it's considered as reasonable, then it's fine for me:)

**Comment by MichaelTunnell** [comment]
> If it's considered as reasonable, then it's fine for me:)

I mean it's not really reasonable in terms of overall resource usage but it's not something Wavebox can solve without not using Electron so if they were to try they would have to rebuild it all. It's an issue that all Electron apps have to deal with and so far Wavebox is the only one I know that has found a reasonable solution with the sleep mode.
