### ISSUE TITLE
Print files from Gmail does not works

### ISSUE THREAD

**Issue by libora** [wavebox/waveboxapp#194]
* Which version of Wavebox are you using? 3.1.7

* Which Operating System are you using? Windows 10Pro 64b

I have PDF file as an attachment in email (Gmail account). I click on them and it is opened in the "preview" window/layer (black background). In the right top corner is an icon for printing this document, but after clicking on this icon then is opened window "My computer". There is no action button and this windows can be only closed. The print process is not started. This problem is with PDF or doc/docx documents. not with pictures. For picture files, the printing process starts correctly (the window for printer selection is opened).

**Comment by Thomas101** [comment]
Thanks for reporting, I'll take a look!

**Comment by Thomas101** [comment]
Also seeing this on macOS

**Comment by htammen** [comment]
Same here with Wavebox 3.1.8 on Mac OS X 10.11.6 (El Capitan)

**Comment by Tahini-123** [comment]
Having the same. Very annoying. Also on El Capitan.

**Comment by bwlange3** [comment]
Any updates on resolving this?  Just started using and will definitely upgrade to pro if this is resolved but I print many PDF's every day so this is a big issue for me.

**Comment by Thomas101** [comment]
After upgrading chromium in our nightly builds we've managed to get together a fix, but at the moment has the side effect of crashing gmail/inbox etc. Hoping to get that resolved before the next release and along with it printing pdfs

**Comment by Thomas101** [comment]
Hi,

We’ve been working on a fix for this which is due to land in the next release. We’re seeing a couple of crashes from chromium with this release at the moment but on the whole it seems to be reasonably stable. If you want to try it out, it would be great to get some early feedback. I’ve put a early build of Wavebox macOS [here](https://wavebox.io/dl/builds/Wavebox_3_1_8_b07d9c6_osx.dmg). Just a couple of things to bare in mind:
* To install just drag over the previous version of Wavebox.
* To enable the new behaviour
  * Open Settings
  * Click on the Advanced tab
  * Toggle `Use experimental window opener` so it’s enabled
  * Restart Wavebox
* When the next version is released this version will update automatically as usual
* If you want to go back to the currently released version of Wavebox, go to the [Downloads Page](https://wavebox.io/download), download and install over the version you’ve updated

Thanks!

**Comment by bwlange3** [comment]
Thanks for the update.  You are definitely getting closer.  Now when clicking the print button in the Gmail preview layer another window opens but nothing populates in that window.  Here is a screen shot for reference.

<img width="1206" alt="screenshot 2017-06-16 11 14 24" src="https://user-images.githubusercontent.com/22185456/27235092-0e385a76-5285-11e7-8938-2849ea276101.png">

**Comment by Thomas101** [comment]
Thanks the feedback, I'll take a look into this one

**Comment by Thomas101** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Print in gmail](https://trello.com/c/XX261nz0/228-print-in-gmail)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.4.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.5.0) and Wavebox beta (3.5.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
