### ISSUE TITLE
Hangouts & Compose pop-out button not working

### ISSUE THREAD

**Issue by Covarr** [wavebox/waveboxapp#202]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Version 3.1.8

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OS X 10.11.6 (this also happens in Windows 10)

In the upper right hand corner of every Hangouts message, there is a little up-right arrow:
![image](http://i.imgur.com/KdO1LzV.png)

When clicked from a proper web browser, this pops the chat out to its own window. In Wavebox, however, it sends it to to the browser, where it displays as a blank window or tab the first time you click it, and repeat clicks simply do nothing.

**Comment by Thomas101** [comment]
Thanks, I'll take a look into this. It could be related to the underlying issue in #187

**Comment by Thomas101** [comment]
Hi,

We’ve been working on a fix for this which is due to land in the next release. We’re seeing a couple of crashes from chromium with this release at the moment but on the whole it seems to be reasonably stable. If you want to try it out, it would be great to get some early feedback. I’ve put a early build of Wavebox macOS [here](https://wavebox.io/dl/builds/Wavebox_3_1_8_b07d9c6_osx.dmg). Just a couple of things to bare in mind:
* To install just drag over the previous version of Wavebox.
* To enable the new behaviour
  * Open Settings
  * Click on the Advanced tab
  * Toggle `Use experimental window opener` so it’s enabled
  * Restart Wavebox
* When the next version is released this version will update automatically as usual
* If you want to go back to the currently released version of Wavebox, go to the [Downloads Page](https://wavebox.io/download), download and install over the version you’ve updated

Thanks!
