### ISSUE TITLE
"Track Package" link won't open in Windows 10

### ISSUE THREAD

**Issue by Kachilero** [wavebox/waveboxapp#205]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.8
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10 ( Version 10.0.15063 Build 15063 )

In Gmail, when you have an email with a UPS ( or other shipping service, I believe, ) tracking number properly formatted in the email ( that is to say, not merely the tracking number, but within an `a` tag, ) it adds a "button" to the list view that would normally open a browser window with the value of the tracking number already filled. 

![ups_track_package](https://cloud.githubusercontent.com/assets/5316481/26400030/caffef46-4044-11e7-8b65-e49438a7467d.png

In the last month or so ( not sure when, I don't get many packages, ) when clicking the "button" a Windows dialog opens saying I need to find an app to "open this"
![ups_track_package_windows_popup]

(https://cloud.githubusercontent.com/assets/5316481/26400082/f0208a74-4044-11e7-8af8-96c2c713f396.png)

If I have Gmail open in a browser window, the expected behavior happens, ie new tab is opened.

This is only a minor UX hiccup but I thought I would bring it to your attention.

Great work, BTW.

**Comment by Thomas101** [comment]
Thanks for the report. I will take a look. Gmail does some funny cross frame communication which is why it could be failing

**Comment by Thomas101** [comment]
Hi,

We’ve been working on a fix for this which is due to land in the next release. We’re seeing a couple of crashes from chromium with this release at the moment but on the whole it seems to be reasonably stable. If you want to try it out, it would be great to get some early feedback. I’ve put a early build of Wavebox macOS [here](https://wavebox.io/dl/builds/Wavebox_3_1_8_b07d9c6_osx.dmg). Just a couple of things to bare in mind:
* To install just drag over the previous version of Wavebox.
* To enable the new behaviour
  * Open Settings
  * Click on the Advanced tab
  * Toggle `Use experimental window opener` so it’s enabled
  * Restart Wavebox
* When the next version is released this version will update automatically as usual
* If you want to go back to the currently released version of Wavebox, go to the [Downloads Page](https://wavebox.io/download), download and install over the version you’ve updated

Thanks!

**Comment by Kachilero** [comment]
Just tested the new version on macOS ( Sierra 10.12.5 ) and while it does open a new window, the window is completely empty. Here's a screenshot with the `devtools` open so you can see the HTML.

<img width="1528" alt="screen shot 2017-06-17 at 9 07 54 am" src="https://user-images.githubusercontent.com/5316481/27253563-ac6be39a-533c-11e7-9754-4ef4181374cb.png">

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox and can be enabled by using the experimental window opener. There’s some instructions on [how to do that here](https://blog.wavebox.io/testing-the-new-window-opener/). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
