### ISSUE TITLE
Dragging image over window then off window causes black screen of death

### ISSUE THREAD

**Issue by chuckreynolds** [wavebox/waveboxapp#210]
* Which version of Wavebox are you using? [e.g. 3.0.0]
`3.1.8`
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
`macOS Sierra 10.12.5 (16F73)`

Dragging a `.png` over from my desktop then not letting go over the email edit screen and putting it back on my desktop.... flashes the image upload "catch zone" but then the wavebox screen turns black and, as far as i can tell, is unrecoverable without restarting the app. 
I can switch to another email account and back and the black screen of death (BSOD) is still present. 

small png, nothing big in file size or pixel size... just a little screen grab section. 

¯\\_(ツ)_/¯   thats all i got. good luck on the bug hunt.

**Comment by Thomas101** [comment]
Thanks! I've just given this a go my end and unfortunately wasn't able to reproduce. After restarting Wavebox, if you try it again does it still happen?

**Comment by chuckreynolds** [comment]
Okay I definitely recreated it.... took me a bit to figure it out. 
SO... compose modal open on bottom right.... drag image from desktop over it... the dotted line shows up fine yada yada ....  the BSOD didn't occur until I dragged the image off to the left over the accounts column... something in there is what made it black out. I did it twice on two different accounts. 

<img width="1440" alt="screen shot 2017-05-30 at 15 08 08" src="https://cloud.githubusercontent.com/assets/46185/26607218/450ba6ae-454a-11e7-98e0-bfd63619a24e.png">

**Comment by Thomas101** [comment]
Hmmm, I'm still not seeing it. Just to double check I'm doing the same as you I've attached a gif (it might take a while to load). [Here's the direct link](https://cloud.githubusercontent.com/assets/103586/26622214/88d4dbd4-45e1-11e7-95c1-09e6cff392db.gif)

![may-31-2017 09-13-17](https://cloud.githubusercontent.com/assets/103586/26622214/88d4dbd4-45e1-11e7-95c1-09e6cff392db.gif)

I wonder if this is down to the graphics card on your mac (if you've got a dedicated card rather than an Intel Graphics chip for example). Could you go to the Apple logo in the top left of your screen and then `About this Mac`. What's listed under graphics? Then if you click on `System Report` you should see your Hardware Overview. There's a modal Identifier in there (mine is MacBookAir6,2 for example), what's that on yours?

There's also a setting you could try toggling under advanced. I doubt this will make any difference but has done on some linux machines so might be worth a try. In Wavebox go to Settings and then click on the advanced tab. Toggle `Ignore GPU Blacklist` so it's off, restart Wavebox and give it another go.

Thanks!

**Comment by chuckreynolds** [comment]
**Graphics** `Intel Iris Graphics 550 1536 MB`
**Model Identifier** `MacBookPro13,2`

I'm also using .png's... fwiw.

video gif thingy - http://i.imgur.com/KNv2lOl.gifv

**Comment by Thomas101** [comment]
Thanks managed to reproduce. Looks to happen more reliably when you drag from the left rather than the right

**Comment by Thomas101** [comment]
Hi, this has been fixed in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
