### ISSUE TITLE
Check for update hangs

### ISSUE THREAD

**Issue by sdmullen** [wavebox/waveboxapp#222]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.8

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OSX 10.12.5

New user of Wavebox, tried clicking "Check for Update" in menu bar under Wavebox and it opens the "Wavebox Updates" dialog and just sits there with the loading bar until I click off the update dialog, regardless of time waited.

![screen shot 2017-06-08 at 09 48 22](https://user-images.githubusercontent.com/4388729/26920079-b5f70b74-4c2f-11e7-96cb-f9e1d89ffef4.png)

**Comment by Thomas101** [comment]
Thanks, we've got a fix for this waiting to ship. Ironically when an update is available it does work correctly :)

**Comment by Thomas101** [comment]
Hi, this has been fixed in the latest version of Wavebox and now that there is a new version available the update dialog should work as expected in the current version :). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
