### ISSUE TITLE
how to set wavebox start up applications

### ISSUE THREAD

**Issue by kuromook** [wavebox/waveboxapp#228]
Hello,I am new in wavebox.
I want to set wavebox to start up on Ubuntu.
but I wonder what command to type wavebox to startup.
 "/usr/share/applications/wavebox.desktop" seems wrong.

* Which version of Wavebox are you using? [e.g. 3.0.0]
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 16.04 LTS

**Comment by Thomas101** [comment]
Hi, I think you should be able to run it directly from /opt/. `/opt/wavebox/Wavebox` should do it. Also if you want to start it hidden you can append the hidden flag, so `/opt/wavebox/Wavebox --hidden`.

Does that work?

**Comment by Thomas101** [comment]
@kuromook did you manage to get it starting up on launch?

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks

**Comment by pestucky** [comment]
I am using Ubuntu 17.10.  I have Wavebox starting on boot using Ubuntu's Startup Application.  But I would like it to start minimized and not splash the screen.  The above command on June12 didn't work.  I don't see where to find the Wavebox version, but I just installed it today.  Thanks for your help

**Comment by pestucky** [comment]
Wavebox has a setting to always start interface minimized, but it didn't work for me.

I resolved the matter using 
  askubuntu.com/questions/663187/how-can-i-run-a-program-on-startup-minimized

Thank you

**Comment by Thomas101** [comment]
@pestucky there's a bug with 3.6.0 which means the `--minimized` flag isn't respected. There's a fix for this waiting to go out shortly... https://github.com/wavebox/waveboxapp/issues/480

**Comment by mobunti** [comment]
btw, yes you can run wavebox via  /opt/wavebox/Wavebox 

On a similar vein, is there any way to start up wavebox and pass a parameter in to specify which screen you want to activate on startup.  If you already have wavebox running and you click to open it again, it does the sensible thing and just takes you to the window you already have open.Because I have several apps in Wavebox - Inbox, slack, my ip camera, mailchimp,hootsuite etc, being able to press say ctrl-alt f12 on my keyboard and run something like /opt/wavebox/Wavebox --screen=4 being the 4th app on the left or /opt/wavebox/Wavebox --screen=HOOT if you gave the ability to add a code onto each app for reference, if i had a ping on my mobile that my ip camera has tracked  motion, i could press a hotkey on my  keyboard to get straight there ;-)

Tony.

**Comment by Thomas101** [comment]
@mobunti the current beta has some global shortcuts to do this. The app will need to be running in the background somewhere but will bring the app to the foreground and switch to an account. You can find the config under Settings > Advanced right at the bottom.

Adding the command line switches should be an easy one though I'll look to add it in!

**Comment by Thomas101** [comment]
@mobunti `--account-index=0` `--account-index=3` etc... will be available in the next beta (3.10.4)
