### ISSUE TITLE
Slack notifications after edit

### ISSUE THREAD

**Issue by rhys101** [wavebox/waveboxapp#238]
* Which version of Wavebox are you using? [e.g. 3.1.8]
* Which Operating System are you using? [all: Windows 10, Mac OSX 10, Ubuntu 14.04]

In Slack, when you go and edit a message this will count as a new unread message - which is fine for others, but not yourself. Steps to reproduce: 
1. Go to a private message
2. Send a message
3. Edit it

Right-click on the Slack icon and clicking Resync resolves it manually (or wait 5 minutes).

**Comment by Thomas101** [comment]
Hi,

We’ve got a fix together for this which is due to land in the next release. If you want to try it out beforehand I’ve put a early build of  Wavebox macOS [here](https://wavebox.io/dl/builds/Wavebox_3_1_8_35a1425_osx.dmg). Just a couple of things to bare in mind:
* To install just drag over the previous version of Wavebox.
* When the next version is released this version will update automatically
* If you want to go back to the currently released version of Wavebox, go to the [Downloads Page](https://wavebox.io/download), download and install over the version you’ve updated

Thanks!

**Comment by Thomas101** [comment]
Hi, this has been fixed in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
