### ISSUE TITLE
Add Obvibase ?

### ISSUE THREAD

**Issue by rol2308** [wavebox/waveboxapp#254]
* Which version of Wavebox are you using? 3.1.8

* Which Operating System are you using? Mac OS 10.12.5

I would like to open and use Obvibase (obvibase.com) in Wavebox, but only the home page appears. Would that be possible to see my obvibase database itself or should i find another online database service ?
Thank you !

**Comment by Thomas101** [comment]
Hi, I'll have a look at why this isn't loading in the Any Web Link URL. On the face of it, it looks like it's calling some chrome apis which aren't available in Wavebox at the moment.

**Comment by rol2308** [comment]
Thank you for your attention about this issue ! I appreciate this :)
(just fyi, I usually use obvibase.com with Opera browser (but sincerely, i have no idea if this means Chrome apis should not be a problem !)

**Comment by Thomas101** [comment]
Hi,

We’ve got a fix together for this which is due to land in the next release. If you want to try it out beforehand I’ve put a early build of  Wavebox macOS [here](https://wavebox.io/dl/builds/Wavebox_3_1_8_b07d9c6_osx.dmg). Just a couple of things to bare in mind:
* To install just drag over the previous version of Wavebox.
* When the next version is released this version will update automatically as usual
* If you want to go back to the currently released version of Wavebox, go to the [Downloads Page](https://wavebox.io/download), download and install over the version you’ve updated

Thanks!

**Comment by rol2308** [comment]
Great ! It works. Thanks for your fast answer :)
