### ISSUE TITLE
Cannot log in to Microsoft Office

### ISSUE THREAD

**Issue by Lauram1610** [wavebox/waveboxapp#257]
* Which version of Wavebox are you using? 3.1.8

* Which Operating System are you using? Windows 10

I've tried adding my work email outlook account to Wavebox but keep getting an error message
![2017-06-14_11-01-24](https://user-images.githubusercontent.com/29450821/27172139-0fac1a66-51ac-11e7-986b-0fb54194bd6c.jpg).

Any advice as to how i can resolve this would be much appreciated

**Comment by Thomas101** [comment]
Hi when you login through your web browser do you use https://outlook.com or https://login.microsoftonline.com/? Does logging in through one of these work?

**Comment by Thomas101** [comment]
Hi I think this is because Wavebox only supports Outlook & Office 365 accounts, but not Exchange at the moment. We're working on adding exchange support into Wavebox shortly. I'm going to collapse this and a few other issues in one (#268) to make it easier to track progress and compatibility. Thanks
