### ISSUE TITLE
Clicking Google Inbox Notifications doesn't open the email

### ISSUE THREAD

**Issue by luispabon** [wavebox/waveboxapp#282]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.12

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 17.04

When a new email arrives, clicking on the notification won't take you to the email in question, merely opens the app.

**Comment by Thomas101** [comment]
Which account type is this with?

**Comment by luispabon** [comment]
Apologies, I should've mentioned this is on Google Inbox.

**Comment by Thomas101** [comment]
Thanks. There is another issue relating to this, but I can't for the life of me find it. The underlying issue is with Google providing a different set of ids for gmail emails (which the api uses) and inbox emails in the UI (that we would be trying to open). We've got a few ideas around doing a fuzzy search to get it working most of the time though

**Comment by luispabon** [comment]
:+1: happy to help testing this

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.2.3. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by luispabon** [comment]
Been trying this and it is already a big improvement, but not quite there yet. 

Upon clicking on the notification, I get taken to the right account, and a search is run at Inbox that shows a single email (the right one though), instead of actually displaying the email.
