### ISSUE TITLE
Urgent: Maximum number of clients reachedFailed to open display -- major failure!

### ISSUE THREAD

**Issue by patrickcurl** [wavebox/waveboxapp#302]
* Which version of Wavebox are you using? [e.g. 3.0.0] 
3.1.12-1 

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
 Arch Linux (Antergos)

Maximum number of clients reachedFailed to open display: :0 error is showing up.. I ran:

lsof -U +c 15 | cut -f1 -d' ' | sort | uniq -c | sort -rn | head -3

per this article : https://unix.stackexchange.com/a/371791

which showed: 372 clients from wavebox... 

I have 10 slack chats,  but most are sleep only till I open them..except the two for work. 
This hasn't happened till I recently updated wavebox.
When this happens some of my windows start closing, and I can't open any other windows till I close Wavebox.

**Comment by Thomas101** [comment]
Hi thanks for reporting. It looks like there's a file descriptor leak when binding the mouse shortcuts which is why it's gone up so much. I've disabled this for the time-being and uploaded a release to the beta channel. There's some instructions on how to [get the latest beta release here](https://wavebox.io/kb/beta-channel). It would be great to know if this fixes it for you

**Comment by patrickcurl** [comment]
Cool thanks, I'll install that later today and let you know how it goes.

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
