### ISSUE TITLE
Calendar links

### ISSUE THREAD

**Issue by Thomas101** [wavebox/waveboxapp#306]
Some Google Calendar links don't work

* Map link when location is provided
* Url link when a url is placed in the description and another user has invited you to the event

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.1.15. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by brianlenz** [comment]
Thanks! I've tested the beta version (3.1.15), and there are still issues.

This links function now, but they are not working correctly. They should open in the default browser, but instead, they are opening in a Wavebox popup window. In our case, we often use these links for Zoom for video conferencing (https://zoom.us/ID URLs). Those links need to open in the browser in order to function properly. Further, after opening and allowing the popup window the load, the parent/main Wavebox window crashes:
![screen shot 2017-07-17 at 7 21 15 am](https://user-images.githubusercontent.com/2305088/28272583-cb7cbf70-6ac0-11e7-840d-a7cff43ac1e9.png)

**Comment by Thomas101** [comment]
Are the links you have just added into the description? I might need to update the capture to only open hangouts, maps etc using the popup window. In the meantime you can now right click on links and use `Open in Wavebox` or `Open in Browser` to get the desired effect.

We're currently tracking the crashing behaviour you've seen there. It's down to some upstream issues with the new window code we're using. If it becomes problematic on your install can disable the behaviour under `Settings` > `Advanced` and by disabling `Use Experimental Window Opener`. A few of the newer window-open fixes aren't implemented in the old window opener code because of technical limitations - just so you're aware.

**Comment by brianlenz** [comment]
There's a link in the "Location" field (which is accessible by clicking the "map" link), and there also are links in the Description. In both cases, they open in Wavebox windows instead of the external browser (but they should always load in the external browser).

Here are the URLs Google Calendar is using:

https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F65821&sa=D&ust=1500392224943000&usg=AFQjCNEIwf9460OqTesNhBkmXWFhG2kkgA

https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F65821&sa=D&ust=1500395824943000&usg=AFQjCNFKXcUnmobuI70IAyR9x9X4e9aNIA

Note that it wraps them in an extra redirect URL; is that perhaps causing the issue?

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.1.16. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by brianlenz** [comment]
Working properly now! Thanks 👍

**Comment by brianlenz** [comment]
I wonder if the changes here may have broken a different feature. Gmail will "clip" emails that are very long:

![screen shot 2017-07-19 at 2 31 10 pm](https://user-images.githubusercontent.com/2305088/28390483-1682a0dc-6c8f-11e7-8ec3-26d9ba09ca8d.png)

These "View entire message" links used to work properly, but now it's opening in an external browser instead of staying in Wavebox and opening in a popup like it used to do...

**Comment by Thomas101** [comment]
Probably not specifically from this fix, but a case that's not being captured by the new experimental window opener (if you were to disable it, I suspect it will work). I've created a new issue for this in #321 so we can triage and fix. Thanks!

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox and can be enabled by using the experimental window opener. There’s some instructions on [how to do that here](https://blog.wavebox.io/testing-the-new-window-opener/). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
