### ISSUE TITLE
libappindicator-gtk2 trouble

### ISSUE THREAD

**Issue by yochaigal** [wavebox/waveboxapp#348]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.2.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Arch Linux 64bit, KDE Plasma 5.10.4

Electron-based apps like Slack, Discord etc do not respond to left-click after installing Wavebox and its dependencies (libappindicator-gtk2). I can still right click on all icons and get the menu, but it makes switching to the various apps kind of a pain.
Removing libappindicator-gtk2, Wavebox runs fine but the icon is a blank square. Other apps do work properly after that, though. Any hope of switching to libappindicator-gtk3 or using another linux systray tie-in? I like Wavebox, but not enough to keep this workaround going.  Thanks

**Comment by Thomas101** [comment]
If memory serves me correctly electron apps use a cascade to decide which library to use which is probably why it affected the other apps you have installed.

As regards the blank square is it just completely transparent as in there's no icon at all, or is it colour black for example? I'll take a look to see if I can reproduce the issue and see if we can get the icon working

**Comment by yochaigal** [comment]
Sorry this took so long to answer, child was sick.
It is a single color - blue, I think.

**Comment by Thomas101** [comment]
No worries - hope all is well now! I haven't had chance to look into this as yet but it's on my list

**Comment by Thomas101** [comment]
Hi, a fix for this has just been released in the latest version of Wavebox. You can get the update by using the File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download).

Unfortunately we couldn't pick out automatically whether the final rendering engine was libappindicator or gtkstatusicon so we've added a configuration option. If you open settings, under the Tray section there's a `GTK icon update mode` option...
![screen shot 2017-08-29 at 12 51 18](https://user-images.githubusercontent.com/103586/29819532-ffa059d2-8cb8-11e7-840f-4520c91b0639.png)
try changing this to `recreate` rather than `update`. If you start to see flickering you may want to try the `static` setting, although this wont display the number of unread messages in Wavebox.
