### ISSUE TITLE
Migrating from tgz install to snap on Linux

### ISSUE THREAD

**Issue by ni-ka** [wavebox/waveboxapp#377]
* Which version of Wavebox are you using? [e.g. 3.0.0]
existing install: tgz - 3.2.0
new install: snap - 3.3.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Fedora 26

Hi,

I would like to switch from tgz install to snap (for easier updates). I have wavebox in /opt/wavebox with several accounts configured. I installed via snap, whoever it did not pick up my settings. How can I migrate my settings to the snap install?

Also - while it might be a snap related problem - the app looks different when launched via snap (background color of the file menu is different for example)

Best,

Nils

**Comment by Thomas101** [comment]
Hi, Snap apps hold their data in a different location and structure because they're security sandboxed. If you want to migrate from the data from your tar to snap then you can use the import/export tools under settings. There's some info on how to do that [here](https://wavebox.io/kb/copying-accounts).

Snaps do look a bit different because they don't use the system dialogs. We've got a release coming up shortly with some improved fonts and some updates the system dialogs, although we haven't tested the dialogs with Fedora yet so they may still look as they do now.
