### ISSUE TITLE
Notification icon sometimes behind border round icon

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#389]
* Which version of Wavebox are you using?
3.3.3beta

* Which Operating System are you using?
windows 10

Sometimes the icon for notification goes behind the border. See below. You see a difference using telegram where it shows and facebook messenger where it does not.

![image](https://user-images.githubusercontent.com/383031/30606638-9f3bf2fc-9d72-11e7-83c2-a6eeb674689b.png)

**Comment by Thomas101** [comment]
It's because facebook adds the red badge to the webpage icon to indicate there are new messages. Wavebox then picks this up as an icon change and simply displays it.

The badge you're seeing on Telegram is added by wavebox which appears when the webpage presents a new notification.

Once we add full support for messenger which will include notifications, unread counts and so-forth we'll make sure that the icon that facebook sets isn't shown. In the meantime to stop it happening, right click on the account and go to Account Settings. From here you can upload a custom icon using the `Change Account Icon` button. Once you've set this the red dot behind the border will no longer appear

**Comment by nmat** [comment]
That makes a lot of sense actually. Thank you for the explanation.

Do you want me to close this issue or keep it in a backlog for future implementation of services?

**Comment by nmat** [comment]
Allowing the service to show notification shows the icon above the image and border it seems.

**Comment by Thomas101** [comment]
I'll close it off for now. We've got a bunch of issues around additional services already :) #130 is the main one. Thanks!
