### ISSUE TITLE
Google Calendar notifications freeze entire interface until Ok is clicked

### ISSUE THREAD

**Issue by ToxMox** [wavebox/waveboxapp#419]
3.4.1 beta on Win 10 X64

When Google Calendar shows an event notification in Wavebox it stalls the entire app until you press OK. I accidentally left Wavebox open over the weekend at work. I came back to a stalled calendar notification and my CPU running at 100% because there were what seemed like hundreds of Wavebox processes running.

**Comment by Thomas101** [comment]
Thanks for reporting. Technically this is a tricky one as `alert()` halts JavaScript execution across the app as per the spec. There may be something we can do though, considering the limited scope of Google Calendar.

In the meantime, you could enable browser notifications, rather than interruptive alerts. This would just popup a normal browser notification and wouldn't lock anything up. If you want to do this, you can find the setting under your Google Calendar settings....

![screen shot 2017-10-16 at 16 27 50](https://user-images.githubusercontent.com/103586/31620430-23c24acc-b28f-11e7-9753-54a8100e72ce.png)

**Comment by ToxMox** [comment]
Ok cool. Thanks for the workaround.

**Comment by Thomas101** [comment]
Whoops - a fix went out for this in the last beta (3.4.2), I just missed this issue when it did. It shouldn't hold up the ui anymore

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.5.0) and Wavebox beta (3.5.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
