### ISSUE TITLE
Select services to show in sidebar

### ISSUE THREAD

**Issue by maroc81** [wavebox/waveboxapp#448]
* Which version of Wavebox are you using? 3.5.0

* Which Operating System are you using? Ubuntu 16.04

It would be nice to allow a user to select which services to show in the sidebar.  As is, it's an all or nothing option.  For example, I would like to add calendar for office 365 to the sidebar in addition to email but I don't want to see all the other services.  Same for gmail and hangouts.  When all services are added the sidebar is too cluttered.

**Comment by nmat** [comment]
You can do this if you right click the account and choose the services in there.

Regarding all services things are added one by one.

**Comment by nmat** [comment]
You can follow this: https://wavebox.io/kb/services-toolbar

and if you scroll further down you can see the services which can be shown or hidden.

**Comment by maroc81** [comment]
Right, but I still want to be able to access the other services through the top bar. So for example, if hangouts were in the side bar, I could go directly to hangouts from the sidebar as messages come in, but I can still access google drive occasionally as needed from the top bar.

The idea here is:  Access frequently used services in the sidebar, and less frequently used services in the top bar.  

I think the only options with 3.5.0 are:
 - Show all enabled services in top bar
OR
 - Show all enabled services in side bar

As I understand it, there is no way to show some enabled services in the sidebar and some/all in the top bar.  Is that correct?

**Comment by nmat** [comment]
ok you want to modify both bars in a custom way.

At the moment I do not believe this is possible. However you can. There are quite some work going on to the interface and maybe this will happen in the future. I thought you just couldn't disable the services in those specific accounts.

**Comment by maroc81** [comment]
Yep that's the idea. I have 6 accounts in wavebox and moving all services to sidebar overruns it. For now, I just have to click on google, then hangouts.  So far, that's the only feature missing that I want.

**Comment by nmat** [comment]
then I am with you. Yeah I do not think it is possible to do that at the moment.

**Comment by Thomas101** [comment]
I think there might be something we can look at doing here. In the meantime, when you show them in the sidebar, have you tried setting them to collapse when the account is inactive? It might help manage multiple accounts

**Comment by nmat** [comment]
I believe this is "some what" fixed due to the new add dialog for wavebox where you can add a indexed service to the sidebar based on your need.

Is there any reason for it to be open at the moment?

**Comment by maroc81** [comment]
That might work. I will have to check it out.  Right now, #482 would get me most of the way there.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. You can now move each service to the sidebar or toolbar separately from the right-click menu.

![screen shot 2018-07-23 at 13 04 37](https://user-images.githubusercontent.com/103586/43075534-19d9a692-8e79-11e8-87d3-35b893a13e34.png)


If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by maroc81** [comment]
Sweet!  #482 is done as well!  Pedro was right, if you vote for him, all your dreams _will_ come true!

**Comment by maroc81** [comment]
I'm seeing a couple of issues with this. One of which, ironically, I think is caused by #482.

1. If I add a service to the sidebar for office 365, it changes the primary service button as well as add it to the sidebar.  I tried to add calendar to the sidebar and now both buttons in the sidebar are set to calendar instead of email with calendar below it.  See screenshot below.  It does this on both of my office 365 accounts for the first service that I add to the sidebar.

![image](https://user-images.githubusercontent.com/8602756/43103709-a7898e10-8e94-11e8-8abe-ade3c145a9f5.png)
My fix for now is to add email to sidebar then calendar so now I have.

![image](https://user-images.githubusercontent.com/8602756/43103805-e8d0b6be-8e94-11e8-9142-8b86a3745902.png)


2. For the one related to #482, I added hangouts to the sidebar which works as expected. However, if I click hangouts in the sidebar then click the main gmail account button, it stays on hangouts.  This may be the expected behavior. I added gmail to the sidebar along with hangouts (similar to what I did with office365 above) and clicking that does go directly to gmail. So now my sidebar looks like below.

![image](https://user-images.githubusercontent.com/8602756/43103667-7db562ee-8e94-11e8-9fab-a527541b16c7.png)


Let me know if I should create new issues for either of these.

Thanks!

**Comment by Thomas101** [comment]
To support this and a bunch of new features we've had to change the way that accounts work in the sidebar slightly. You've basically got a grouping (the large icon) and then the individual services within it.

By default the grouping doesn't have an icon, whereas each of the services has its own default icon (e.g. the Google hangouts logo) and then some of the ones that sync (e.g. your gmail account) have their own icon.

To provide an icon for the grouping we run through the services in-order looking for a specific set/synced icon, then if we can't find one of these we use the default icon of the first service. So to explain what's happened in the two cases above...

1. O365 doesn't have an icon for your account (maybe there's not one set?) so it's only got default icons available. When you swap mail and calendar around it's using whichever one is first.
2. Gmail has an icon that's synced, so we're always using that one regardless of the order.

We did it this way because we thought it would give the most similar experience when users update (i.e. nothing changes). We've also added the option to set your own icon in settings for the grouping which will keep it consistently the icon you set...

![screen shot 2018-07-24 at 09 26 02](https://user-images.githubusercontent.com/103586/43126113-bb4ce958-8f23-11e8-8b03-0fdbc7ea52ee.png)


All that said though we're happy to take feedback on this, perhaps we can be a bit cleverer about which icon to pick or what to do! For the most part we want it to just-work with minimum configuration, but also want to give tools for those who want to customize the behaviour and appearance

**Comment by maroc81** [comment]
With the latest beta it appears to be working the way I expect.

![image](https://user-images.githubusercontent.com/8602756/43344825-d31c9eea-91b0-11e8-9981-8a6257e38056.png)

With my setup like the screenshot above, what I see is
1. Clicking on hangouts/calendar always loads the respective service
2. Clicking the main account icon loads the last selected service

:+1: 

Only feature missing now is system notification for calendar events :)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
