### ISSUE TITLE
[Contributing Guidance] displaying push notifications

### ISSUE THREAD

**Issue by TheWithz** [wavebox/waveboxapp#465]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.5.1beta
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
[solus3](https://solus-project.com/)

In reference to Issue #131 

In addition to Google classroom, I've finished Google music, Project FI, and Google Admin, in my fork. However, Google classroom and Google Music have push notifications and I wanted to implement that before issuing a pull request. Using google hangouts (communication) as a model I was looking into handling that for the two new services, However, I got a bit lost on the way and was wondering if you could offer some guidance on how to integrate the push notifications. Classroom would need a count of unread notifications the same way Hangouts does, but google music would simply need system notifications to display and disappear.

**Comment by Thomas101** [comment]
Wow that's awesome! The implementation is a little bit messy at the moment and we've got plans to make it simpler, but I'll see if can help with our current setup.

Depending on what you want to do there's a couple of ways of propagating count at the moment. Google Calendar just puts an unread indicator when a notification fires. This one is similar to do and can be pretty much just done by setting the correct configuration on the model, but I think you're probably looking to do more than that. Hangouts scrapes the unread count from the dom and then propagates this up into the app, which I think is closer to what you're trying to do. I'll run through the way hangouts works, hopefully this will help.

If you need anything else explaining or have more questions feel free to ask. Or if you want to open half a PR, I can take a look at a few things etc :)

---

The first thing to do is create the members that are going to be loading the custom code and responding to it. This sits in two halves, some in the mailboxes window and another section in the guest page. The code that runs in the guest page doesn't have direct access to the data so is kind of used as a slave to the WebView window.

The custom webview class for hangouts which basically composes the different components into a single view. Take a look at [GoogleMailboxCommunicationWebView.js](https://github.com/wavebox/waveboxapp/blob/master/src/scenes/mailboxes/src/Scenes/AppScene/Mailbox/MailboxWebView/Google/GoogleMailboxCommunicationWebView.js). You should notice it preloads a googleCommunication script by setting the `preload` attribute on webview and also responds on some ipcEvents that come back using the `ipcMessage` event.

Once you've got this, you've then also got [googleCommunication.js](https://github.com/wavebox/waveboxapp/blob/master/src/guest/src/preload/googleCommunication.js) and [GoogleCommunication.js](https://github.com/wavebox/waveboxapp/blob/master/src/guest/src/Google/GoogleCommunication.js) that sit in the guest repo. This code runs in the guest page and checks the dom for changes, posting them back to the hosting webview as they change.

Back in the WebView ([GoogleMailboxCommunicationWebView.js](https://github.com/wavebox/waveboxapp/blob/master/src/scenes/mailboxes/src/Scenes/AppScene/Mailbox/MailboxWebView/Google/GoogleMailboxCommunicationWebView.js)) there's an `ipcMessage` event that handles incoming messages from the guest page. This listens for the unread changed count and does two things...
1. Pops up a notification through `processPushedMailboxNotification` (although if the page displays html5 notifications by default, this wouldn't be needed).
2. Updates the unread count on the model through the `mailboxActions.reduceService` call using the `GoogleCommunicationServiceReducer.setUnreadCount` reducer

---
Now you've got the two halves of the story to getting the count, you'll need to store it. Take a look at [GoogleCommunicationServiceReducer.js](https://github.com/wavebox/waveboxapp/blob/master/src/scenes/mailboxes/src/stores/mailbox/GoogleCommunicationServiceReducer.js). This basically writes the changes to the model using the `reduceService` call. In this instance a count and a changed time.

In the model [GoogleCommunicationService.js](https://github.com/wavebox/waveboxapp/blob/master/src/shared/Models/Accounts/Google/GoogleCommunicationService.js) we now need to expose these fields with a few defaults. These fields are overrides that exist in CoreService. The sync engine uses these to decide what to display etc.

* `get unreadCount() { }` should return the number of unread items.
* `get trayMessages() {}` returns the message that display in the app tray. Although because we only pull basic info about hangouts at the moment, this is just a shim that gives `x unread messages`
* `get unreadCountUpdateTime() { }` is used for internal housekeeping of the changed time

Finally to tell the sync engine what's supported by this model, you'll need to change some of the static props...

* `supportsUnreadCount` - set this to true because we're now going to support these
* `supportsNativeNotifications` - true, if you're using `processPushedMailboxNotification` or false if you're relying on html5 notifications
* `supportsTrayMessages` - true if you want to add anything into the tray icon (e.g. 10 unread messages...etc)
