### ISSUE TITLE
Support for saving session with gooogle apps and saml

### ISSUE THREAD

**Issue by topochan** [wavebox/waveboxapp#52]
* Version 3.1.3
* OS Ubuntu 16.04

When google apps is using a saml provider (like okta), wavebox is not able to save the session or the account information, I have to do the whole login every time I start the app

**Comment by BenJetson** [comment]
This was fixed a while ago. You can make Wavebox save your session information for SAML accounts with the "Artificially Persist Cookies" setting under "Accounts".

![image](https://cloud.githubusercontent.com/assets/10427974/24915944/9e9f17fc-1ea6-11e7-84c0-7be857c023aa.png)

I use this setting with my work account, since they use a SAML login provider, and it keeps me signed in for a couple of weeks or so. When it logs you out thereafter, just right click on the account icon and click "Re-Authenticate" and sign in again.


![image](https://cloud.githubusercontent.com/assets/10427974/24916047/05f19d9e-1ea7-11e7-9ba5-58bbeb792209.png)

**Comment by topochan** [comment]
Many thanks, didn't notice the option in the documentation
