### ISSUE TITLE
[question] How to share settings between source build and snap ?

### ISSUE THREAD

**Issue by ben8p** [wavebox/waveboxapp#557]
As a daily driver, I use the snap version.
However, I would also like to help with the development.
therefore I have installed the source as well.

When starting wavebox from the source, all accounts configured with the snap are gone (even after login).
Is there any way to share the account across the 2 installs ?

**Comment by nmat** [comment]
The only way I would think is to use export/import of the accounts.

**Comment by Thomas101** [comment]
This works out of the box when using the tar/deb/apt repository, but because of the way Snap sandboxes app & OS data it stores it in a different location.

I haven't tried this, but you might be able to Symlink the snap data directories into the non-snap ones - however I suspect there may be permission issues with this. There's some info on where app data is held [here](https://wavebox.io/kb/data-locations) if that helps

**Comment by ben8p** [comment]
Thanks, I will try that

**Comment by Thomas101** [comment]
@ben8p did you have any luck with that?

**Comment by ben8p** [comment]
Couldn't try yet. I will be away from keyboard for 2 weeks. I will check when I am back

**Comment by ben8p** [comment]
I confirm a symlink work : 
`ln -s ~/snap/wavebox/current/.local/share/wavebox ~/.local/share/wavebox`
