### ISSUE TITLE
[feature request]: Notifications with emoji translation

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#561]
* Which version of Wavebox are you using? 3.10

* Which Operating System are you using? windows 10

* Description:
This is more of a investigation if it is possible and can be implemented using electron.

Can the emoji texts be translated to emoji icons? Instead of saying something like:

:+1: or :slightly_smiling_face: etc.

however this is the Slack variant. I am wondering if the notification can read this from the service and translate it? Or how would that work?

**Comment by Thomas101** [comment]
Oh I see, `:thumbsup:` to be :thumbsup:

I've just tried pasting an emoji into a notification and that shows up as you'd expect, so as far as OS level supported ones go, this should be a find and replace job. As for the custom team emojis and newer variants, they won't work as they use embedded images.

Trouble is finding a list of shortcodes to actual emoji characters. I had a quick google but couldn't find a list of one to the other...

**Comment by nmat** [comment]
I did do some digging also before on electron if there was a service -> notification type of code to do this. Since it would have been much better to have the service itself do the translation and wavebox just present that in the notification area. (less things to keep track of)

However....the reason for the request is to lower the output of the notification that comes in. You are mostly interested in the text and not the emoji itself (and its a bit annoying with the long running text for the emoji sometimes)

This can wait of course...its a interesting feature to have though.....maybe it needs to be based on the per service level?

**Comment by Thomas101** [comment]
The notifications come from the services in one of three ways. Slack runs in mixed mode meaning it gets them off the WebSocket push or scraped out the UI (whoever gets the info first).

Because the slack store handles each of these, we can re-write the notification content before it gets pushed out.

Should just be a case of replacing the body content in these two lines... 
https://github.com/wavebox/waveboxapp/blob/master/src/scenes/mailboxes/src/stores/slack/slackStore.js#L523
https://github.com/wavebox/waveboxapp/blob/master/src/scenes/mailboxes/src/stores/slack/slackStore.js#L547
...the main work is just finding the huge list of codes to emojis after that you're pretty much home-dry. I'll do a bit more googling when I'm waiting for a build to finish up or something later

**Comment by nmat** [comment]
interesting.....I am going to dive into this also. Just need to see if I can get the build running on my windows 10 machine it failed yesterday :(

**Comment by Thomas101** [comment]
Found a library that does it :)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
Tested on windows 10 and beta release now for slack and that works just fine. :)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
