### ISSUE TITLE
Other Service URL Alignment

### ISSUE THREAD

**Issue by andyunleashed** [wavebox/waveboxapp#574]
* Which version of Wavebox are you using? - 3.10.0

* Which Operating System are you using? - Mac OSX 10.13.3

Along the top bar of a service like Basecamp the URL appears for the current "page" you're on in the app. 

The issue is that the url is not center aligned in the bar which makes me twitch! (Screenshot attached).

Not a big deal, just a visual improvement that could be nice!

<img width="1610" alt="screen shot 2018-02-11 at 19 33 15" src="https://user-images.githubusercontent.com/1426079/36077470-3ba42a12-0f63-11e8-9bbd-fae3627a8a6e.png">

**Comment by Thomas101** [comment]
At the moment it's aligned centrally in the remaining space after the buttons have been rendered....

<img width="1610" alt="36077470-3ba42a12-0f63-11e8-9bbd-fae3627a8a6e" src="https://user-images.githubusercontent.com/103586/36144722-e4f28c28-10a6-11e8-9c7b-deba7b8681ef.png">

...which is probably why it appears a little off. Aligning dead center is a real pain because of the buttons on the left-hand-side.

I wonder if it would be best to just align left like most browsers. This would remove the problem alltogether. Great to hear what you think!

**Comment by andyunleashed** [comment]
Yeah definitely get why it is where it is. I'd maybe go left aligned because it's not something you can interact with anyway, more informational.

**Comment by Thomas101** [comment]
I've just pushed this out in the beta channel of Wavebox, version 3.10.3. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
