### ISSUE TITLE
Slack badges not updating consistently

### ISSUE THREAD

**Issue by jason0x43** [wavebox/waveboxapp#590]
I've added two Slack teams to Wavebox. I'm typically using one most of the time, and only look at the other when it has updates. It seems like within the last patch version or two Wavebox has become very inconsistent about updating the badge for the less-used team. I still get desktop notifications when someone mentions me, and the badge will update if I manually resync that team, but it doesn't update reliably on its own (or at least not in a timely fashion).

* Which version of Wavebox are you using? [e.g. 3.0.0]

3.10.3beta

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

macOS

**Comment by Thomas101** [comment]
There's a fix for this one coming in 3.10.4beta tomorrow :)

**Comment by jason0x43** [comment]
Excellent

**Comment by Thomas101** [comment]
Looks like the beta may be delayed a couple more days. There's a couple of things that you can do in the meantime though...

1. Right click on the account in the left and pick re-sync. This should force it to reconnect and the badge should update consistently until you restart Wavebox next
2. The bug was introduced in this beta cycle and isn't in the 3.10.0 stable version so you could download the stable binary. To do this change your update channel under `Settings > Advanced` then download wavebox from https://wavebox.io/download. Install as usual.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by jason0x43** [comment]
Preliminary results look good.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
