### ISSUE TITLE
Annoying WhatsApp notification sound!

### ISSUE THREAD

**Issue by jssagu** [wavebox/waveboxapp#597]
How do I turn this WhatsApp notification sound off?

I have turned notifications off under the main settings and Whatsapp. I am getting no sound for emails but only for Whatapp whenever somebody sends a message!

Driving me mad and on verge of removing the Whatsapp feature.

Thanks

**Comment by nmat** [comment]
In wavebox you have the option to turn off the notification and sound for a specific service.

If you right click the service for whatsapp there will be a notification setting in there. If that does not work you can go to General in preferences and try turning off the sound there.

However if you have turned the notification sound off for whatsapp then the notification sound "should" be off.

**Comment by jssagu** [comment]
Hello, I turned all notifications off but am still getting the sound. I even uninstalled and reinstalled the software and tried again but to no avail...

**Comment by nmat** [comment]
Thats odd.

Are you using chrome browser and allowed for whatsapp to send notifications through there and chrome still sends the sound and not wavebox?

**Comment by jssagu** [comment]
I am just using the WaveBox software as standalone for my emails and WhatsApp. The sound is also coming through on another computer as well..

**Comment by jssagu** [comment]
![screen shot 2018-03-04 at 11 49 27](https://user-images.githubusercontent.com/37015824/36945182-4c6c7c38-1fa2-11e8-9050-075eaa1d5939.png)
![screen shot 2018-03-04 at 11 49 59](https://user-images.githubusercontent.com/37015824/36945183-4c8d064c-1fa2-11e8-82da-6a510828057f.png)

**Comment by jssagu** [comment]
As you can see, sound notifications is turned off. Even when notifications are turned off for emails, I am still getting sound from Whatsapp

**Comment by Thomas101** [comment]
The notification sound setting in Wavebox configures the sound from the Notification api. It looks like WhatsApp is just playing a sound when a new message arrives, which is why it continues to play and the setting is ignored.

WhatsApp does have settings to configure these though. If you open up your WhatsApp Settings through the 3 docs at the top and then go to `Settings`
![1](https://user-images.githubusercontent.com/103586/36969815-79b45500-205e-11e8-9c56-42c71b154c07.png)


There's a `Notifications` section in here which has options for Sounds, Showing Previews etc. If you disable Sounds here it should stop playing
![2](https://user-images.githubusercontent.com/103586/36969848-88724c00-205e-11e8-8450-2ea1f1f1ed5f.png)

**Comment by jssagu** [comment]
Thank you! This worked! :D
