### ISSUE TITLE
Right Click Context Support

### ISSUE THREAD

**Issue by cglusky** [wavebox/waveboxapp#65]
WaveBox 3.1.3 on Win7x64

Recently moved from WMail to WaveBox hoping right click context menu support would be better.  It's not.

Specifically, please allow us to do something constructive with the hover tooltip when the mouse is placed over someones name/email in Inbox.  Such as right click and at least see COPY EMAIL ADDRESS.  

Stronger integration with Google Contacts in that context menu would be preferred but I would settle for just being able to copy an email address, so I can move it someplace useful.

Overall, I am concerned that WaveBox is seeking to be jack of all and master of none with all these new services being added before even basic context menu support is added to the services that originally existed.  Sorry to be so negative.  Loved WMail.  But if you are going to wrap a business model around this product, which I think you should, be prepared for higher expectations.  Yet I don't think proper context menus are setting the bar very high.

**Comment by Thomas101** [comment]
Hi Coby, thanks for the feedback. It would be good to know which hover tooltip you're talking about. Is it these ones?
![screen shot 2017-04-12 at 18 06 00](https://cloud.githubusercontent.com/assets/103586/24970031/c0076e94-1faa-11e7-9552-a81109babac6.png)

**Comment by cglusky** [comment]
Yes, those are the ones.  Perhaps it makes most sense to have a few options in the tooltip itself rather than require a right click.  Probably work better for tablet users?

**Comment by Thomas101** [comment]
I agree with you, they are a little lackluster when it comes to doing anything useful with them. Wavebox & WMail both work by hosting a website within them, in this case `inbox.google.com`. Pretty much all the user interface you see within it is provided by Google rather than us and if you use internet explorer to load up your inbox you'll also see the same behaviour.

We can provide tweaks to what Google have already, but keeping those tweaks reliable is another problem. Google use some tooling to reduce the size of their page which has the side effect of changing the underlying structure of the page when update it. This makes hooking in to different events and parts of the page quite difficult.

Perhaps something we can look at is searching for email address strings within the page (e.g. looking out for `myemail@mywebsite.com`) and seeing if we can get those to come up as links automatically or something. The popover in the screenshot would still remain pretty much as it is, but if you expand the email heading and right click an email address it would give you the option to copy that rather than the selected text
