### ISSUE TITLE
libappindicator-gtk2

### ISSUE THREAD

**Issue by yochaigal** [wavebox/waveboxapp#654]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.4.2

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Arch Linux 

Hello! Any chance you'll move off of libappindicator-gtk2 at some point? 
I have a lot of electron apps running alongside wavebox; I can't click on any of their tray icons (I have to right-click) while libappindicator-gtk2 is installed. I'm on KDE.

**Comment by nmat** [comment]
Do you mean the other electron apps has tray icons and are not clickable?

From what I know electron does have some limitations on the tray icon part from 1.8.x docs (https://electronjs.org/docs/api/tray):

Platform limitations:

* On Linux the app indicator will be used if it is supported, otherwise GtkStatusIcon will be used instead.
* On Linux distributions that only have app indicator support, you have to install libappindicator1 to make the tray icon work.
* App indicator will only be shown when it has a context menu.
* When app indicator is used on Linux, the click event is ignored.
* On Linux in order for changes made to individual MenuItems to take effect, you have to call setContextMenu again.

**Comment by Thomas101** [comment]
We haven't got any specific plans to move of `libappindicator` at the moment, to be honest. If you don't have `libappindicator` installed though, Wavebox (and most other electron-apps) will fall back to `GtkStatusIcon`. Both of these have slightly different behaviour.

If you're using KDE, `GtkStatusIcon` might be a better fit, I think it responds to left click rather than right click. It's a little bit down to personal preference though and you may find some apps don't work as well with `GtkStatusIcon`.

**Comment by yochaigal** [comment]
Sure.
Though in my distribution libappindicator is a dependency for wavebox.

**Comment by Thomas101** [comment]
Perhaps that's something we could look at loosening up. Some of the new repositories list items as optional or recommended.

How have you been installing Wavebox? (e.g. snap package, yum repo, apt repo etc etc...)

**Comment by yochaigal** [comment]
From the Arch User repository.

**Comment by Thomas101** [comment]
The AUR repository is maintained by someone in the community at the moment. Might be worth removing libappindicator manually to give it a go and seeing if this works better - then raising the issue with the repo maintainer. They seem pretty responsive to comments and suggestions!

**Comment by yochaigal** [comment]
Removing libappindicator-gtk2 makes it *so much better*. I can see a whole
left click UI that's never been there before!
However, the icon is a weird blue box. Anyways, I'll tell the AUR
maintainer.

**Comment by subosito** [comment]
As suggested by @yochaigal, I've just removed `libappindicator-gtk2` as required dependency from wavebox-bin for v3.14.5.

**Comment by yochaigal** [comment]
Thanks guys!
This is much better now, especially for my other electron apps with tray
icons. I *do* wish I could get a working tray icon that doesn't require
recreating itself, but this is still pretty great.
