### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by hana0211** [wavebox/waveboxapp#675]
* Wavebox Version: [e.g. 3.14.5]
* Operating System & Version: [Windows 10]

> wavebox@3.14.5 install:all C:\wave\waveboxapp-3.14.5
> node scripts/installAll.js

npm install: C:\wave\waveboxapp-3.14.5
[    ..............] | loadDep:yeoman-generator: sill resolveWithNewModule nan@2.10.0 checking installable status

Stayed here for a long time, unable to compile？？？

**Comment by nmat** [comment]
hmmm I am using windows 10 and managed to get it working following instructions from first page.

Can you tell us a bit more of the steps you have taken and also if this is GIT version?

Also....what node version are you using?

**Comment by nmat** [comment]
interesting..

and which step did it fail on?

**Comment by hana0211** [comment]
npm install and then npm install:all stop here 
unable to compile

**Comment by Thomas101** [comment]
The `install:all` script just runs `npm install` in a bunch of directories. You could be seeing the hang because of a network issue.

If you try it again does it work? If not try going into each of these directories in turn and run `npm install` does it fail on one in the same way or does it manage to install correctly?

* `waveboxapp`
* `waveboxapp/src/app`
* `waveboxapp/src/guest`
* `waveboxapp/src/crextensionApi`
* `waveboxapp/src/scenes/mailboxes`
* `waveboxapp/src/scenes/content`
* `waveboxapp/src/scenes/monitor`
* `waveboxapp/src/scenes/print`
* `waveboxapp/src/scenes/keychain`
* `waveboxapp/src/scenes/traypopout`

**Comment by nmat** [comment]
@hana0211 any update if you managed to get it working?

**Comment by nmat** [comment]
I have tested again today to compile using a new computer install with nodejs latest LTS and all worked to compile here.

@hana0211 did you manage to get it sorted? 

@Thomas101 maybe this can be closed?
