### ISSUE TITLE
When wavebox.io is down it's not possible to start wavebox

### ISSUE THREAD

**Issue by roccolord** [wavebox/waveboxapp#689]
* Wavebox Version: 3.14.6-1
* Operating System & Version: ubuntu 16.04
* (Linux only) Install method: apt
* Account type (if applicable): gmail

**Expected & actual behavior**
start app, doesn't start

**Steps to reproduce**
make sure wavebox.io is down, start app

**Is the bug persistent or intermittent?**
only when wavebox.io is down

**Comment by Thomas101** [comment]
Hey - it should be back up and running now.

Apologies for the downtime earlier today - it was due to all of Amazon's US-EAST-2 facility becoming offline for around 30 minutes, which affected our servers (amongst quite a few others!).

I'll modify the timeout at startup in Wavebox to be 10 seconds rather the system's default network timeout - this will be released in the next beta.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.7. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by PeteJodo** [comment]
Wait so what was the issue? Does Wavebox still rely on wavebox.io being up or was it that, due to some default, it was hanging and couldn't boot?

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
