### ISSUE TITLE
Cursor stuck on one character selection

### ISSUE THREAD

**Issue by asferens** [wavebox/waveboxapp#715]
* Wavebox Version: 3.14.6
* Operating System & Version: Mac OSX 10.13.5
* Account type (if applicable): All

**Expected & actual behavior**
This has been persistent but intermittent for as long as I can remember with Wavebox. Every so often the cursor will get its self stuck in what seems like a constant one character selection. This makes typing almost impossible as that selection always deletes any character in front of it if you jump back into any sentence. Should have raised this a while ago, it's the only thing that stops Wavebox from being amazing!

The only way i've found to temporarily resolve the issue is to close & re-open the app.

**Steps to reproduce**
Unsure to date.

**Is the bug persistent or intermittent?**
Persistent through all releases to date, but intermittent.

**Comment by Thomas101** [comment]
@asferens which input source are you using? There was some issue with typing Chinese characters some time ago, I'm wondering if it could have come back up

**Comment by asferens** [comment]
No extensions or extra applications doing window based actions. I will grab a screenshot & check those factors next time it occurs. I've screenshoted the Wavebox task monitor while everything is running fine to compare when it does pop up. (Any other areas I should monitor in app?)

Input source is just the usual keyboard, and only standard characters.

**Comment by asferens** [comment]
Would you consider Slack an extra application? It's probably set off within Slack more than any other account type, but that may be due to the amount of communication I do through it vs standard email.

**Comment by asferens** [comment]
Recreated! It's slack only, other accounts within Wavebox are unaffected. This is what i'm stuck with even though no character is selected:

![screen shot 2018-06-27 at 2 39 33 pm](https://user-images.githubusercontent.com/2108521/41950100-97d9d2ee-7a18-11e8-9795-14905f836034.png)

**Comment by Thomas101** [comment]
Thanks for the extra info, the more we can narrow it down the easier it is to fix!

* Are there any steps that you can do to recreate it? E.g. navigate with the keyboard arrows, click somewhere etc...
* When it does freeze, are you able to:
  * Switch Accounts in Wavebox
  * Interact with the slack page in any way? (e.g. clicking on a different channel)
* When it happens next time, are you able to right click in the Slack page and then pick `Inspect`. In the window that pops up, click the console tab. Are there any errors?

There are a couple of settings you can try changing in Wavebox. Because you're only seeing it with Slack I don't think these will make any difference, but it might be worth trying. Go to settings > Advanced and...
* Enable `Isolate Account Processes`
* Disable `In process spellchecking` (Spellchecking will still work, it might just be a little slower).
* Restart the app

**Comment by nmat** [comment]
I wonder......if this could be based on where cursor is located. I know that on some systems...lets say mac or linux you can have marked text....if you then move outside of the window where the text cursor is located but mouse is in focus on a different place that the focus on text will go away.

Its far fetched I know.

**Comment by Thomas101** [comment]
@asferens would you be able to give this a try with the latest version of [Wavebox (4.0.0)](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) to see if you're still experiencing the issue. Thanks

**Comment by asferens** [comment]
Will do! So far so good, up until this point it has been persistent and across more than just Slack, also Inbox/Gmail

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment, I'm happy to-open and I’ll take another look. Thanks

**Comment by asferens** [comment]
Sadly still getting it, running the latest MacOS 10.14 x Wavebox 4.3.0

**Comment by Thomas101** [comment]
Thanks for the update, I'll have another look into this

**Comment by asferens** [comment]
I've just had this happen to me in the dedicated Slack app - probably a bigger OS problem, closing.
