### ISSUE TITLE
[Bug] wavebox mini - icon differences from git and beta

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#736]
* Wavebox Version: 3.14.8beta
* Operating System & Version: windows 10 

**Expected & actual behavior**
Icons are not the same on git and beta

**Steps to reproduce**
Undock from tray

**Is the bug persistent or intermittent?**
Persistant.

**Screenshots**

![image](https://user-images.githubusercontent.com/383031/43083580-2135a724-8e97-11e8-907e-a50c3066b4f2.png)

**Comment by Thomas101** [comment]
Should look like so...
![screen shot 2018-07-23 at 16 10 14](https://user-images.githubusercontent.com/103586/43085566-2da0544a-8e93-11e8-973f-d7410e3726dd.png)
...but the icon ref was wrong. When building from git, if you don't have a fontawesome pro license key in your `.npmrc` the app won't be able to pull the libs from npm and so we default to only using free icons.

For the most part we can substitute icons with that of a different weight (e.g. the exit icon in your screenshot), however there are some icons with no free-equivalents (e.g. the arrow icon we use for restoring to the tray).

The mapping that we use for pro is in the [FARegistry.pro.js file](https://github.com/wavebox/waveboxapp/blob/master/src/scenes/wbfa/FARegistry.pro.js) and for the free in [FARegistry.free.js](https://github.com/wavebox/waveboxapp/blob/master/src/scenes/wbfa/FARegistry.free.js). We then sideload the correct one in using webpack depending if we've detecting the pro version of the icons in `node_modules`

**Comment by nmat** [comment]
odd...I still see the normal square icon on git for windows 10.....is it possible that the fontawsome part is not compiled in correct? I did do: npm run clean:all and redid the compile but still the icon is only the square.

Any suggestion of what I can test?

**Comment by Thomas101** [comment]
Yeah you will :). [Fontawesome](https://fontawesome.com/) icons come in two flavours, pro and free.

The icon in question is only available with the paid-for pro version. The license we have for these allows us to use the icons in the app but doesn't allow us to distribute them in the open-source project. If you have a license key setup, the pro version of the icons get pulled in when you run `npm install`.

When building Wavebox from source, there's two options...
1. If you have a fontawesome license [add it to your npmrc as described here](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers). Then when running `npm install` on Wavebox it will pull the pro icons in
2. If you don't have a fontawesome pro license we've added a mapping into Wavebox which will still allow it to build and run, but it will only use free icons.

Most of the pro-icons have semi-equivalent free icons, for example we use [sign-out (regular)](https://fontawesome.com/icons/sign-out?style=regular) for the quit button, but can substitue it with [sign-out-alt (solid)](https://fontawesome.com/icons/sign-out-alt?style=solid).

For the square/non-square one, we use [Arrow-alt-square-up (regular)](https://fontawesome.com/icons/arrow-alt-square-up?style=regular) but there isn't one similar enough to this to drop in, which is why we settled on the square icon.

That said if you think there's a more suitable free icon, we can change it for that (that's the mapping used in [FARegistry.free.js](https://github.com/wavebox/waveboxapp/blob/master/src/scenes/wbfa/FARegistry.free.js)). Or we also use [material-icons](https://material.io/tools/icons/) in the app which are completely free, so we can use all of those too.

**Comment by nmat** [comment]
I might be wrong here. But why then not use material-icons, I mean if you are basing the UI on material-ui already it kind of makes sense to continue using the same icon sets from them also? Or am I wrong?

Its not my call but it kind of makes sense to me to follow the same standard?

**Comment by Thomas101** [comment]
Material-icons is normally our first port of call, but we weren't able to find anything suitable in the library for this icon.

Happy to look at changing them though if there's one that makes more sense, we can also build composites of multiple icons (e.g. the `show in main window` is actually two icons).

**Comment by nmat** [comment]
Yeah I looked at the icons and seems hard to figure out a good replacement. Hmmmm

**Comment by Thomas101** [comment]
That's the conclusion we came to aswell :-(

**Comment by Thomas101** [comment]
I've updated the ones that dump out to a basic square to be something a little bit more useful :)

![screen shot 2018-07-25 at 14 57 01](https://user-images.githubusercontent.com/103586/43205696-d7d8a956-901b-11e8-8a46-c8b6fa3374cc.png)
![screen shot 2018-07-25 at 14 57 09](https://user-images.githubusercontent.com/103586/43205698-d7f2fdce-901b-11e8-8e0b-c41d129147b5.png)

**Comment by nmat** [comment]
That definitely looks a lot better. Good job!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.9. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks
