### ISSUE TITLE
Application can't be run

### ISSUE THREAD

**Issue by 7krasov** [wavebox/waveboxapp#760]
* viacheslav@viacheslav-N501VW:~$ snap list wavebox 
Name     Version  Rev  Tracking  Publisher  Notes
wavebox  3.14.6   109 stable wavebox -
* Ubuntu 18.04.1
* Snap package

**Expected & actual behavior**
When running the app it can't be opened and no process in a system. It doesn't start

**Steps to reproduce**
Just click on the app in a LaunchBar/dock

**Is the bug persistent or intermittent?**
Bug is persistent

**Additional information**
content of dmesg output afrer run:

[ 1014.342959] audit: type=1400 audit(1534315839.563:108): apparmor="DENIED" operation="ptrace" profile="/snap/core/5145/usr/lib/snapd/snap-confine" pid=14900 comm="snap-confine" requested_mask="read" denied_mask="read" peer="unconfined"

Last success usage after reboot: Friday, the 10th of August 2018
Bug spotted: today (15th of August)

Yesterday (14th of August) I've installed kernel 4.18.0. Not sure but maybe this is the reason. Also this day I've upgraded my system

Start-Date: 2018-08-14  21:27:32
Commandline: apt upgrade
Requested-By: viacheslav (1000)
Upgrade: gir1.2-gmenu-3.0:amd64 (3.13.3-11ubuntu1, 3.13.3-11ubuntu1.1), python-samba:amd64 (2:4.7.6+dfsg~ubuntu-0ubuntu2, 2:4.7.6+dfsg~ubuntu-0ubuntu2.2), libwbclient0:amd64 (2:4.7.6+dfsg~ubuntu-0ubuntu2, 2:4.7.6+dfsg~ubuntu-0ubuntu2.2), libarchive13:amd64 (3.2.2-3.1, 3.2.2-3.1ubuntu0.1), gdm3:amd64 (3.28.2-0ubuntu1.3, 3.28.2-0ubuntu1.4), gir1.2-gdm-1.0:amd64 (3.28.2-0ubuntu1.3, 3.28.2-0ubuntu1.4), samba-libs:amd64 (2:4.7.6+dfsg~ubuntu-0ubuntu2, 2:4.7.6+dfsg~ubuntu-0ubuntu2.2), libgdm1:amd64 (3.28.2-0ubuntu1.3, 3.28.2-0ubuntu1.4), python3-distupgrade:amd64 (1:18.04.21, 1:18.04.24), ubuntu-release-upgrader-core:amd64 (1:18.04.21, 1:18.04.24), samba-common:amd64 (2:4.7.6+dfsg~ubuntu-0ubuntu2, 2:4.7.6+dfsg~ubuntu-0ubuntu2.2), libsmbclient:amd64 (2:4.7.6+dfsg~ubuntu-0ubuntu2, 2:4.7.6+dfsg~ubuntu-0ubuntu2.2), smbclient:amd64 (2:4.7.6+dfsg~ubuntu-0ubuntu2, 2:4.7.6+dfsg~ubuntu-0ubuntu2.2), samba-common-bin:amd64 (2:4.7.6+dfsg~ubuntu-0ubuntu2, 2:4.7.6+dfsg~ubuntu-0ubuntu2.2), libgnome-menu-3-0:amd64 (3.13.3-11ubuntu1, 3.13.3-11ubuntu1.1), ubuntu-release-upgrader-gtk:amd64 (1:18.04.21, 1:18.04.24), gnome-menus:amd64 (3.13.3-11ubuntu1, 3.13.3-11ubuntu1.1)
End-Date: 2018-08-14  21:27:44

**Comment by Thomas101** [comment]
Hi, thanks for reporting. Given it a try my end and I see the same behaviour. When I tried `snap run wavebox` from the terminal the error I saw was...

```
cannot perform readlinkat() on the mount namespace file descriptor of the init process: Permission denied
```

It looks like a snap confinement issue with the 4.18.0 kernel and snap version `2.34.3`. There's some discussion on the snap forum about this [here](https://forum.snapcraft.io/t/cannot-perform-readlinkat-on-the-mount-namespace-file-descriptor-of-the-init-process-permission-denied/6743/5) and a few suggested solutions.

I gave a few a try and the one that worked for me was running `sudo snap refresh core --edge` to update to snap `2.35~pre3`. Seems to work okay with that version. (If it breaks something else, you can run `sudo snap refresh core --stable` to go back to `2.34.3`).

Alternatively, if you don't want to go to the edge version of snap you can use one of the other install methods for Wavebox. There's an apt repo available with instructions on our [download page](https://wavebox.io/download). It's worth noting, that because of the snap confinement, when you install Wavebox using a different install method it's unable to import your data - you'll need to setup your accounts afresh.

**Comment by 7krasov** [comment]
Thanks for the quick answer, Thomas101! Could you please tell me whether I can log in into ubuntu package application and get all my already attached accounts and settings or not?

**Comment by Thomas101** [comment]
I think you could grab the `_db.json` files `~/snap/wavebox/current/.local/share/wavebox` and place them in `~/.local/share/wavebox/`.

This will bring your accounts across but you'll need to log back into each in turn. If you've got a Wavebox pro membership make sure you sign in with your pro-account through the app settings. [This KB](https://wavebox.io/kb/using-wavebox-pro-on-another-machine) might help

**Comment by Thomas101** [comment]
Let me know if you have any problems though!

**Comment by 7krasov** [comment]
Sorry, didn't catch your point about 'but you'll need to log back into each in turn.'... Could you explain more exactly? what turns? could I log in through a repository package one more time once?

Just for notice: other (not wavebox) snap apps are broken (not sure that all)

**Comment by Thomas101** [comment]
Copying the `_db.json` files across will bring some of the data that Wavebox uses. Mainly your settings, which accounts you have added, how you've configured those accounts etc. However it wont bring things like cookies and logged in sessions.

This means that if you copy the `_db.json` files, Wavebox will load with your accounts but, if you've got a gmail account added for example, it will prompt you for your username and password to login the first time you run it.

**Comment by 7krasov** [comment]
Thanks a lot! I see my cases now and no questions anymore. I think the issue could be closed
