### ISSUE TITLE
Upgrade not clean for Ubuntu through Ubuntu Software center and downloaded DEB package

### ISSUE THREAD

**Issue by GreyCorbin** [wavebox/waveboxapp#781]
* Wavebox Version: 3.14.1 to 4.0.0
* Operating System & Version: Ubuntu 18.04
* (Linux only) Install method: Debian installer, Ubuntu Software center

**Expected & actual behavior**
Expected an install option in Ubuntu Software Center that would upgrade/replace the current version, or that the downloaded installer would upgrade/replace the current version.  

Actual was no Install button in the Software center despite showing that it was offering the new version.  The downloaded installer looked like it installed, but it did nothing. 

(Lost entire setup on moving to new version (partly my fault))

**Steps to reproduce**
I assume that just having an Ubuntu system with 3.14.X installed and then try to upgrade will be enough.

**Is the bug persistent or intermittent?**
only one chance to see it.

**Additional information**
The partly my fault part is that, seeing no other option to get the new version and not being patient enough to file a bug report and wait for an answer, I uninstalled the current version.  Then I could install through Ubuntu Software center as expected.  All my settings and Apps are now gone, though.  

I'm so spoiled by the options to install via a GUI route that I sometimes forget you have the package center option.  I'll be setting that up for future use.  (Yes, I'm a Windows user trying to become a Linux user.)

Not blaming.  I just want to insure it gets looked at and that others may see this and not do what I did.

**Comment by nmat** [comment]
Did you use the provided source from wavebox.io or something else?

**Comment by GreyCorbin** [comment]
I did.  I used the "Open with Software Install" to install the package after download.

**Comment by Thomas101** [comment]
Hi, the reason behind is this because the app in the Ubuntu App Store is packaged up as a snap package. Snap packages have additional confinement restrictions on them which means they run within a sandbox.

One of these restrictions is not having unrestricted access to the filesystem without explicit consent (e.g. through a file/open dialog). Because of this restriction we have to store app data within the snap namespace (`~/snap/wavebox/current/.local/share/wavebox`) rather than where the app would normally if installed without snap (`~/.local/share/wavebox/`).

This means that if you're switching between a non-snap install and a snap install we don't have access to the app data, nor a way to detect if it was ever there! The only way to do this on a fresh install would be to ask the user to manually navigate to `~/.local/share/wavebox/` and open the directory so we could import data - but obviously this would be overly cumbersome.

If you don't want to continue using the snap version (e.g. update through the apt repo/install manually each time, etc...) then your user data should still be in `~/.local/share/wavebox/`. If you're happy to continue using the snap version then it will continue to work aside from this.

If this were to happen again, version 4 does include cloud backup and restore which would get you half-way. You could restore your settings and accounts but would need to sign back into each one. Generally though we don't recommend changing install method unless one poses an issue

**Comment by Thomas101** [comment]
Thinking about the way forward from this, I'm not sure there's anything automagical that we can do about bringing the app data in or out from the snap install because of the confinement. If there are any ideas floating around though, would love to hear them - it could be something that would help others.

**Comment by GreyCorbin** [comment]
I have no issues using apt to upgrade.  Installing from the other options seem to work just fine.

I just wanted others to know that upgrading via one of the other options might not go as planned.

**Comment by Thomas101** [comment]
I've added a [KB article here](https://wavebox.io/kb/data-when-reinstalling-wavebox) about this - hopefully it will help anyone in the future :)
