### ISSUE TITLE
Inbox Shutting Down on March 2019

### ISSUE THREAD

**Issue by ladislas** [wavebox/waveboxapp#788]
Hi there --

Google announced that they will be shutting down Inbox in March 2019.

[Source](https://www.google.com/inbox/)

It's very sad news for me and I guess for many others as well...

What does it mean for Wavebox?

Best,  
-- Ladislas

**Comment by Thomas101** [comment]
It's sad to see that Google is retiring Inbox - as an avid Inbox user myself it breaks my day-to-day workflow and going back to Gmail is a bit of a pain. I'm going to miss things like bundles, nice inbox zero picture, tasks and a few other things. Hopefully we'll see these coming to Gmail soon (fingers crossed).

That said, we've known that Inbox would have a retirement date set for a while and have been waiting for an official date since they took the New Gmail out of beta. As far as Wavebox is concerned we'll continue to support Google Inbox until it is retired and try to help those still using Inbox transition across to Gmail.

We've already started this with version 4 of Wavebox that launched this week. You can now add a Gmail service to any account - including those set up as Google Inbox account (Just right click on the account and pick `Add Service`. From here pick Gmail and you'll be good to go!).

It's sad to see Inbox have the shutters pulled, but we're excited to see what the Gmail team have in store and we'll continue to support Gmail as a first-class citizen in Wavebox :-)

**Comment by Thomas101** [comment]
I'll stick a `more-info` label on this for now and leave it open, then close in a couple of weeks if that's okay :)

**Comment by Thomas101** [comment]
Hi, the latest beta (version 4.5.12) has some extra tooling and helpers to migrate from Google Inbox to Gmail. We've also added a blog, with some more general information and tips on how to make the transition [here](https://blog.wavebox.io/inbox_to_gmail/).

If you want to give the beta a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel)

Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
