### ISSUE TITLE
Wavebox window freeze while application is in use and a notification is received

### ISSUE THREAD

**Issue by asadana** [wavebox/waveboxapp#809]
* Wavebox Version: 4.2.0
* Operating System & Version: Fedora 28 (Edit/Update: KDE Plasma Desktop)
* (Linux only) Install method: Snap Package
* Account type (if applicable): Multiple Slack workspaces (Gmail once/twice as well)

**Expected & actual behavior**
Expected: Interactions with Wavebox are not frozen.
Actual: Wavebox window freezes while typing and a notification is received from a different app in Wavebox.

**Steps to reproduce**
While using Slack to type a message, if a notification is received from a different workspace or a different app, like GMail, the Wavebox window freezes for half a minute, then resume.

**Is the bug persistent or intermittent?**
Persistent

**Additional information**
Interesting thing is that after the Wavebox window unfreezes, all the input from keyboard while the window was frozen is restored. I would guess that's it's simply a threading problem where the notification blocks the rendering of the app temporarily?

**Comment by Thomas101** [comment]
Hi, thanks for reporting. Can you check if you're using the default or enhanced notification provider and try switching it to see if that makes any difference? The setting can be found under Settings > Notifications
![screen shot 2018-09-27 at 12 04 44](https://user-images.githubusercontent.com/103586/46142051-969de280-c24d-11e8-944c-e36b90e0fdf4.png)

**Comment by asadana** [comment]
Thank you for getting back to me on this.
I was using the "Default" option, I have switched to Enhanced as of this morning, I will test it today and report back.

**Comment by asadana** [comment]
So far I cannot reproduce this issue using "Enhanced" notifications.

However Enhanced notifications don't seem to be following the desktop placement for notifications. But that's an unrelated and less important issue.

**Comment by Thomas101** [comment]
Thanks for the update. The enhanced notifications use a completely different stack to the default ones which is why I suspect this is the case.

I've just given this a try with Fedora 27 and 28, but it allows me to continue typing as expected. My first reaction is that it could be something to do with the snap version of Wavebox - these sometimes have slightly different behaviours and quirks to the non-snap versions. Can you run `snap --version` from the terminal to see what comes up?

It might be worth trying the non-snap version of Wavebox too, just to rule out if it is the case. The snap version doesn't share the same data directory with non-snap versions so should live side-by-side okay. The tar version at https://wavebox.io/download is probably the fastest way to do this

**Comment by asadana** [comment]
`$ snap --version
snap    2.35-1.fc28
snapd   2.35-1.fc28
series  16
fedora  28
kernel  4.18.10-200.fc28.x86_64
`
Possible root cause might be compatibility issue specific to the Desktop Environment I am using, KDE Plasma.

I'll switch over to the non-snap version today and re-test the Default notifications on it.

**Comment by Thomas101** [comment]
Thanks, I've put Fedora KDE on a machine here and tried the snap install, but I'm not seeing the same freezing.

Mines a clean install, fully updated, but is there anything else that I should look to tweak or configure (e.g. different window manager, virtual desktop setup etc...)

**Comment by asadana** [comment]
Nope, I don't have anything else that would affect this.

So far I have been unable to reproduce this issue using the tar and rpm packages.

If you cannot reproduce it on Fedora KDE with snaps, then it might be something on my end that is triggering this.
Going to close this issue for now, will reopen if I can narrow down what is triggering it consistently, that way you don't have to waste your time.

Thanks for looking into this :)
