### ISSUE TITLE
Add account workflow not working

### ISSUE THREAD

**Issue by joseph-devito** [wavebox/waveboxapp#839]
* Wavebox Version: 4.4.0
* Operating System & Version: Mac OSX Mojave
* Account type gmail/inbox

**Expected & actual behavior**
Any way I try to add an email account results in an infinite loop of signing in and never getting added to wavebox

**Steps to reproduce**
click avatar on top right of wavebox window> click add account> opens a browser window and asks me to sign in> sign in > nothing gets added to wavebox/never re-routes back to wavebox

OR

wavebox>preferences>accounts>pick an account> Add account > this opens a window to "add your next app to wavebox"

**Is the bug persistent or intermittent?**
No issue in previous versions when I have tried, Have yet to be able to add a second account this version

**Comment by nmat** [comment]
have you tested other accounts also? Or is this central to just gmail?

**Comment by joseph-devito** [comment]
Other gmail accounts, yes -- no other types of accounts since this "add account" feature seems to be central to gmail/google account

**Comment by nmat** [comment]
so its the first account you are trying to add right now?

In that case that makes sense. 

I just tested to add my own gmail account again and it seems to have worked fine. So probably need some more information in order to proceed here.

In preferences you see that there is an option for Data & Sync. There you can check if there is anything you can do with for example the clean of expired accounts or similar. There are few options there to check if any of them work for you. (please read what each of them tell you also) it will mean that you will clean up some cache and be logged out etc.

**Comment by joseph-devito** [comment]
No it’s an additional account that I’m trying to add. I also signed out of
everything and tried which didn’t work. 2 gmails , 2 gmail addresses — it
doesn’t actually add accounts it just opens a web page and asks you to log
in but it’s not the typical “authorize this app” website it’s just a
regular login that doesn’t route back to wavebox. Happy to provide any more
info that I can for you

**Comment by joseph-devito** [comment]
Thank you so much!  Did this functionality change? I could have swore I was
able to easily do this in past versions.  Looks like this worked though,
thank you

**Comment by Thomas101** [comment]
There's been some change between version 3 and 4 of Wavebox.

Adding a Gmail service (along with its own google drive, calendar etc etc) as an entirely separate account to the sidebar remains the same (just by clicking the add button at the bottom-left of the screen). Adding two gmail services to the same account is something new that we added in version 4. This is what you've done in this case
