### ISSUE TITLE
Office 365: Google Drive links - Showing in office 365 account Advanced settings

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#846]
* Wavebox Version: 4.4.0
* Operating System & Version: Windows 10
* Account type (if applicable): Office 365

**Expected & actual behavior**
Onedrive or read from the account? Google drive is not connected to this account.

**Steps to reproduce**
Go to preferences for the account of office365

**Is the bug persistent or intermittent?**
Persistent

**Additional information**
Not sure but maybe preferences should read from the actual account you are editing and what drive is used or not used?

**Comment by Thomas101** [comment]
This is something that changed when we went from 3 - 4. Originally the option was only available when you added a Gmail or Google Inbox account.

From a users perspective, the Google Drive links option works for more than just Google Drive. For example, it applies to most `*.google.com` urls (e.g. Gmail, etc...). At the moment, you could add an office365 account and then attach a bunch of Google Services, custom urls etc.

We could probably look across all the account services and choose to hide the option if we don't think it's relevant.

I guess the only case this would fail is you did the following...
* Add any weblink account at `https://bing.com`
* Navigate into `https://drive.google.com`

The option would now not be shown, as the url for the service is `bing.com` but the behaviour change would be applied because you're actually on `drive.google.com`.

Part of me agrees that we should intelligently remove it, but another part of me thinks we should keep it there for consistency :-/

**Comment by nmat** [comment]
Agreed, I guess I would expect it to show based on what is read inside wavebox (if I have google drive, if I have onedrive, then show options based on what is available to wavebox)

However its my 2 cents I guess.

**Comment by Thomas101** [comment]
I totally agree with you on that one. My only concern is because of the "any weblink" account type there's a bit of ambiguity as to whether it will kick in or not.

Maybe the thing to do here is to show the setting if there's a google-y account type or an any weblink account type. That way it removes the ambiguity and lets us hide it off when it's definitely not relevant :)

**Comment by Thomas101** [comment]
I think for the time being we're going to leave the Google Drive option in the Advanced section as it is hidden away a little bit. If there are more exceptions to the window opening rule, such as Google Drive and it starts to grow we'll re-look at this again though.

At the moment, the fact that you can add any kind of account into any grouping making this quite difficult to pin when to show the setting and when not to.
