### ISSUE TITLE
Gmail Input box doesn't scroll when filled

### ISSUE THREAD

**Issue by CheechGe** [wavebox/waveboxapp#858]
* Wavebox Version: [e.g. 3.0.0]
4.4.0
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
Windows 10
* (Linux only) Install method: [e.g. Debian installer, Snap Package, Tar, Apt-Repo, etc...]
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...]
GMail
**Expected & actual behavior**
Some information about what you expect to happen and what actually happens.

If the gmail input window is completely filled the bottom part of the last line is cut off.  If the data on the last line goes to the right edge or terminated via an enter key the window is not scrolled up so that more data can be entered.  The down arrow keys or the page keys also can not be used to position the window so that more text can be added.   The only way I have found to remedy the situation is to but the input window into full screen mode. 

My expectation is that that the window should automatically be positioned so that more text can be entered.

**Steps to reproduce**
Are there any steps that we can take to reproduce the bug?

Just enter more text then would fit in the window 

**Is the bug persistent or intermittent?**
Do you only see it sometimes or does it always happen?

Happens all the time

**Screenshots**
Screenshots often help us narrow down a bug more easily.

Attached.
![wavebox_05](https://user-images.githubusercontent.com/3653639/48872558-976b7480-edb7-11e8-8511-85d744d883e9.png)

**Additional information**

**Comment by Thomas101** [comment]
@CheechGe would you be able to send a screenshot of the input box when you're no longer able to type

**Comment by CheechGe** [comment]
Sorry I attached the incorrect screenshot, the correct one is attached.  It's the gmail input box when the Compose button is selected.


![wavebox_06](https://user-images.githubusercontent.com/3653639/48954849-20e68800-ef19-11e8-8dfa-09a24e52658b.png)

**Comment by CheechGe** [comment]
Here is 2 more screenshoots.  

In the first one the last line was entirely filled then when one more digit was entered it word wrapped as expected but the last digit would not appear until Full screen mode was set.

![wavebox_07](https://user-images.githubusercontent.com/3653639/48955512-3f01b780-ef1c-11e8-92bb-a72ade45877e.png)


This screenshot has the same thing (except using a different digit) and using typomatic to force a word wrap with more digits.  Again the only way I could find to see the data on the word wrapped line and to continue entering text was to set Full screen mode which requires saving the email as a draft and then reopening it.

![wavebox_08](https://user-images.githubusercontent.com/3653639/48955636-cf3ffc80-ef1c-11e8-8ad4-52f1220ffbfb.png)

**Comment by nmat** [comment]
This same effect happens on chrome with gmail compose. Its a bug in gmail more rather then wavebox.

I can reproduce it on both parts where the text goes below the formatting line.

**Comment by nmat** [comment]
Thunderbird I think uses a different lib to render how it works with mail (not using the web to render the compose message)

Chrome and also wavebox uses the web client and is using chrome library to render how compose should look. Not tested vivaldi browser but if it uses the same type of rendering engine and api to render compose messages then it should look fairly the same.

There "could" be api settings to fix this but if you also check you will see the popout is a popout so its hard to say that it would take presidence over the content. If you click the "A" underscored icon you will see that the popout is not going to be shown.

Then the compose window will show as intended. So if you encounter this issue then I suggest to hide that bar by clicking on A (formatting options).

**Comment by Thomas101** [comment]
It's down to the formatting options button - the formatting options appear as a popover rather than a toolbar.

For example, you're seeing this, with the last two lines hidden by the formatting bar (I've actually written one, two, three, four)...
![a](https://user-images.githubusercontent.com/103586/49003753-86758700-f15a-11e8-9be9-12191c25f06c.png)

If you click the A with the underline, it will hide the bar and it will scroll to the bottom automatically as you'd expect...
![b](https://user-images.githubusercontent.com/103586/49003764-8d03fe80-f15a-11e8-9bf7-d7410b06468e.png)

I think the popover keeps the last state it was in for new emails, so for example if it was open last time, it will be open next time and vice-versa. This is probably stored different for each browser, which is why Vivaldi didn't show the edit bar when you tried it.

Some of the Gmail team keep an eye on the Official Gmail Help Forum, so it may be worth reporting it there. There's already a bunch of questions and conversations about the formatting options, but I couldn't see a similar one to this. [Here's the link](https://productforums.google.com/forum/#!topicsearchin/gmail/formatting$20options)
