### ISSUE TITLE
Have to re-add all accounts and apps after installing the latest version

### ISSUE THREAD

**Issue by LesterU** [wavebox/waveboxapp#86]
* Which version of Wavebox are you using? - 3.1.5

* Which Operating System are you using? - Windows 10

I have installed the last two updates and found that it doesnt bring in all my accounts and apps. I have to re-add them all again, including all my settings and app icons. 

Am I doing something wrong here??

**Comment by Thomas101** [comment]
Hi  Lester sorry about this. If you auto update it should work, but there was a bug on windows that meant that if you reinstall you have to re add your accounts. This is fixed in 3.1.5 but unfortunately still means that the upgrade from 3.1.4 to 3.1.5 still has the bug. When 3.1.6 is released it should work as expected

**Comment by LesterU** [comment]
Ok, great!
