### ISSUE TITLE
Add support for main window custom JS

### ISSUE THREAD

**Issue by rfgamaral** [wavebox/waveboxapp#867]
Just like main window custom CSS support but for JS.

This would help me easily work around #866 and it's something already implemented per account/service, shouldn't be too time consuming adding support for the main window, right?

Or, perhaps, is there a reason this was not added in the first place when main window custom CSS support was added?

**Comment by Thomas101** [comment]
We haven't done this because most of the code is wrapped up as a react app and there are no globally exposed hooks to the react code that would be all that useful. It makes interfacing with what the app does really difficult without needing to recompile the source with the additional code hooked in.

I guess you could use DOM mutation observers to change the underlying elements on render but not sure if that would be helpful.

Do you have any js getters and setters in mind? My gut feeling here is expanding the CSS API would be easier both from a styling and interfacing standpoint

**Comment by rfgamaral** [comment]
> I guess you could use DOM mutation observers to change the underlying elements on render but not sure if that would be helpful.

This was mostly my idea... I understand that JS tweaking would be limited but it would still open a few tweaking possibilities with a bit of work.

> Do you have any js getters and setters in mind? My gut feeling here is expanding the CSS API would be easier both from a styling and interfacing standpoint

Completely agree. But like I said, my request for this feature is simply to workaround #866, because I don't have any other use for it (for the moment at least).

**Comment by Thomas101** [comment]
> Completely agree. But like I said, my request for this feature is simply to workaround #866, because I don't have any other use for it (for the moment at least).

With that in mind, I'll close this one off for now. I think until there are some solid use cases, expanding/improving the CSS hooks as in #866 is the way to go on this.
