### ISSUE TITLE
Keyboard shortcut Cmd + Ctrl +Space on macOS does not work anymore

### ISSUE THREAD

**Issue by peterkraume** [wavebox/waveboxapp#874]
* Wavebox Version: 4.5.0
* Operating System & Version: macOS 10.13.6
* Account type (if applicable): all

**Expected & actual behavior**
In almost every Mac app, the keyboard shortcut Cmd + Ctrl + Space pops up a window to insert emoticons.
This used to work also in Wavebox but since the latest update, this doesn't work anymore.

**Steps to reproduce**
Go to a text field in any app within Wavebox and press Cmd + Ctrl + Space. Nothings happens then.

**Is the bug persistent or intermittent?**
All apps within Wavebox are affected. If I open the respective web app in a regular browser, the shortcut Cmd + Ctrl + Space works as expected.

**Comment by peterkraume** [comment]
Sorry, I wrote the wrong Shortcut command. Of course I use Cmd + Ctrl + Space. I haven't changed any shortcuts and in every other app this still works as expected.

I edited my initial report to fix the shortcut I use.

**Comment by Thomas101** [comment]
Thanks, wanted to check that, just in case 😀

We've tried here on macOS 10.13.6 and 10.14.1 but it seems to come up as expected. I'm thinking that I must be doing something different, or there's a difference in the machine setup...
* Where have you been trying it? (e.g. gmail compose)
* Do you have any extensions installed?
* Have you changed any of the Wavebox keyboard shortcuts under Settings?

**Comment by peterkraume** [comment]
- The error occurs in every input field (I use Slack, Flowdock, WhatsApp, Facebook messenger)
- I don't have any extensions installed
- I haven't changed any keyboard shortcuts

**Comment by mathieutu** [comment]
Hi, I can confirm that I **can't** reproduce this bug here. 😕

**Comment by Thomas101** [comment]
Might sound daft, but does a restarting the machine help?

**Comment by peterkraume** [comment]
Nope, a machine restart didn't solve the problem. Meanwhile I'm using Wavebox 4.5.4. Still the same issue.

**Comment by peterkraume** [comment]
I have added accounts for Slack, Flowdock, WhatsApp, Trello, Facebook Messenger, Pocket, Grammarly and Mastodon.

My `settings_db.json` looks like this:

    {"news":"{\"latestHeadline\":\"New Stable Release: LastPass, UI Updates, Sleep Shortcuts, App Grouping\",\"latestSummary\":\"We're delighted to introduce a significant release to Wavebox today. This release includes a selection of great new features, plus improvements to the way Wavebox works.\",\"latestTimestamp\":1536673944040,\"lastSeenTimestamp\":1522145056447}","app":"{\"hasSeenAppTour\":true,\"hasSeenAppWizard\":true,\"hasSeenOptimizeWizard\":true,\"lastSeenAccountMessageUrl\":\"https://wavebox.io/desktop/message/trialexpire/0days?c=a4f70fd8-3923-4b47-9c3a-e4669961a9b1&s=38d32ccac204467a8121f8b1a363213f&expired=1\"}","language":"{\"spellcheckerEnabled\":false}","ui":"{\"showSleepableServiceIndicator\":true,\"showDefaultServiceSleepNotifications\":false,\"accountTooltipMode\":\"ENABLED\",\"sidebarControlsCollapsed\":true}","os":"{\"notificationsSilent\":true}"}

**Comment by Thomas101** [comment]
Thanks @peterkraume this is turning into a real head scratcher. I've still not been able to reproduce it here. I've tried on 3 machines, with the same accounts you have setup etc and just can't seem to get it to fail.

I guess we could try a bare-bones setup to rule out interference from any added accounts et, but I suspect it will be the same. What happens if you try the following...
* Quit Wavebox completely
* Move `~/Library/Application Support/wavebox/` somewhere else
* Start the app again
* Go to the Help menu and `Restart in Safe Mode`
* After restart, go to Settings > Keyboard Shortcuts. Expand any of the panels and click in one of the fields. Try Control+Cmd+Space here. (These input fields are the most least customized fields in the app without needing to add an account etc)

To go back to normal,
* Quit Wavebox completely again
* Move your previous `~/Library/Application Support/wavebox/` back into place
* Start the app back up

The other things the team here have been talking about, is whether it could be something to do with language setup on your Mac.
* Under `System Preferences` > `Language & Region` which language do you have setup? 
* Under `System Preferences` > `Keyboard` > `Input Sources` which input source are you using? Is `Automatically switch to a document's input source` checked?

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
