### ISSUE TITLE
Account tooltip disappears before you can click on any service (Windows only)

### ISSUE THREAD

**Issue by tnaseem** [wavebox/waveboxapp#880]
* Wavebox Version: [e.g. 3.0.0]

4.5.3

* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]

Windows 10

* (Linux only) Install method: [e.g. Debian installer, Snap Package, Tar, Apt-Repo, etc...]
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...]

All accounts.

**Expected & actual behavior**

When you hover over the account icon, the tooltip appears. However, when you want to select anything within the tooltip (one of the services, for instance), as soon as you move the mouse away from the account icon, the tooltip menu disappears.

This only happens on Wavebox on Windows 10. On the Mac, the tooltip menu stays visible.

**Steps to reproduce**

Just hover over one of the Account icons and move the mouse to select something from the tooltip that appears.

**Is the bug persistent or intermittent?**

Persistent.

**Screenshots**
![snag_881fdbc](https://user-images.githubusercontent.com/1317345/49706216-6a5d0400-fc89-11e8-843f-f201db3b94e2.png)

**Comment by Thomas101** [comment]
I'm struggling to reproduce this. Are you using a touchscreen device or anything other than a mouse?


The hover area is pretty well defined, in that you have to stay within the correct area otherwise it will hide. (Highlighted in green).
![49706216-6a5d0400-fc89-11e8-843f-f201db3b94e2](https://user-images.githubusercontent.com/103586/49738663-caeb4180-fc87-11e8-9d28-6b1f50e32900.png)

For example if you stray out of this via another icon it will hide (orange path)...
![49706216-6a5d0400-fc89-11e8-843f-f201db3b94e2 copy](https://user-images.githubusercontent.com/103586/49738695-e5bdb600-fc87-11e8-96f4-b1435faf3b21.png)

Are you able to see any defined boundaries that cause the popover to hide?

**Comment by tnaseem** [comment]
My machine is a mini-tower gaming/development rig. No touchscreen.

It hides regardless of how I move the mouse across. I normally try and keep the movement horizontal within the confines as you've illustrated.

I've now deleted my install on Windows and wiping everything from AppData to see if there's anything that may have been lingering there. Currently installing a fresh copy and importing settings from my Mac! Will report back in a sec...

**Comment by tnaseem** [comment]
Ok. So, after much playing around with settings and wiping data, etc, I've discovered that if I **enable** Wavebox's titlebar in Settings (I normally have this off), the tooltips stay visible.

They only exhibit the *disappearing* issue when the titlebar is disabled.

Hope this helps!

**Comment by blankpoint** [comment]
I have exactly the same problem since this feature was added. The hover area seems to only be initial round icon. As soon as I go off it toward the tooltip box, the tooltip box itself disappears. Windows 10 x64 with 3 monitors. This happens on all of them. Each of the monitors has different DPI settings (1, 1.25, 1.5). Closed Logitech mouse software to test if it was that, and problem persists.

I don't know if it's related, but the release blog post also mentions a new right-click menu on the sidebar, and that doesn't show either. I get a normal Windows "restore, maximize, close... pop-up menu when right-clicking there.

**Comment by tnaseem** [comment]
> I don't know if it's related, but the release blog post also mentions a new right-click menu on the sidebar, and that doesn't show either. I get a normal Windows "restore, maximize, close... pop-up menu when right-clicking there.

Actually, just realised. Same here too. But this also works fine if I enable the titlebar again.

**Comment by blankpoint** [comment]
I can confirm that tnaseem's solution works, but hopefully you can fix this so we don't need the superflous Windows titlebar.

**Comment by Thomas101** [comment]
Nice find on the titlebar, was able to reproduce after that!

I've put a fix out for this in 4.5.5 :)

**Comment by dalescher** [comment]
I have the same problem (windows 10) and cannot find the titlebar option in settings. I installed wavebox yesterday and it's up to date (10.0.104.1).
