### ISSUE TITLE
Ubuntu 18.04 fonts screwed due to wavebox 'recomendation'

### ISSUE THREAD

**Issue by ddoice** [wavebox/waveboxapp#886]
* Wavebox Version: 4.5.3
* Operating System & Version: Ubuntu 18.04
* (Linux only) Install method: .deb

**Steps to reproduce**
On first run apps recommends to install Windows fonts on Linux.

**Expected & actual behavior**
Expected to improve experience.
Result: all my system fonts are changed, chrome console, terminal fonts, sublime text...
Tryed to unistall with but now my fonts are really weird.

**Additional information**
IMHO you should remove this 'advice'.

**Comment by Thomas101** [comment]
Installing the Windows fonts is an optional step which ensures that all fonts are available when using the app. These can't be bundled in Ubuntu or Wavebox because they require the agreement of a seperate Microsoft license.

We follow the same advice as given across the web (for example [here](https://www.ostechnix.com/install-microsoft-windows-fonts-ubuntu-16-04/) & [here](https://www.makeuseof.com/tag/how-to-install-microsoft-core-fonts-in-ubuntu-linux/)) to use the recommended font package, maintained by Ubuntu in the [Ubuntu repository](https://packages.ubuntu.com/bionic/ttf-mscorefonts-installer).

The font installer package will have installed the fonts to `/usr/share/fonts/truetype/msttcorefonts` which could be removed. There's some more help on the web as regard removing the fonts on the ubuntu forums [here](https://askubuntu.com/questions/57735/how-to-remove-ttf-mscorefonts-completely/461998).

**Comment by Thomas101** [comment]
Can you email some screenshots to support [at] wavebox.io and we can pick it up there?
