### ISSUE TITLE
Retry or Quit from "No Internet" Screen

### ISSUE THREAD

**Issue by zyigo** [wavebox/waveboxapp#888]
* Wavebox Version: 4.5.5
* Operating System & Version: Windows 10

**Expected & actual behavior**
Cannot click to refresh/retry/test connectivity on the no internet screen. Also cannot quit without task manager to try again.

**Steps to reproduce**
Have no internet. Try and click Retry.

**Is the bug persistent or intermittent?**
Every time I have seen this screen, I have to restart the app after quitting with Task Manager.

**Screenshots**
![annotation 2018-12-18 092049](https://user-images.githubusercontent.com/2831291/50119241-41023080-02a6-11e9-80c4-fc7612737566.jpg)

**Additional information**
Another major issue is -> it is impossible to quit from this screen without task manager.

**Comment by Thomas101** [comment]
Hey, thanks for reporting.

I'll get a fix in for only being able to quit via the task manager. This is because the tray icon hasn't yet been created - but the app isn't taking note of this.

As for failing to connect, I'm not able to reproduce this. On a box here, once I've reconnected to the web the app either picks this up automatically or pressing retry launches correctly. It would be good to have some info about the setup when this occurs. For example, is it that you've just woken the machine up. Not connected to the web yet, etc...

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
