### ISSUE TITLE
have to reauthenticate multiple times day

### ISSUE THREAD

**Issue by bmurphy1976** [wavebox/waveboxapp#923]
When running Wavebox 4.5.10, I have to reauthenticate all of my Google accounts multiple times per day.  I have 4 accounts that I use.  3 of the accounts I login to twice (one Calendar, one Email), the 4th is email only.

I feel like this started about a week ago.  Normally I rarely have to reauthenticate.

<img width="1136" alt="screen shot 2019-02-05 at 9 00 36 am" src="https://user-images.githubusercontent.com/270488/52282526-3f5bfd00-2926-11e9-9cb4-17802233fec6.png">

**Comment by Thomas101** [comment]
Hi, thanks for reporting. Normally needing to reauthenticate like this is really rare, normally after a year or more. When this happens, Google rejects the auth tokens which is why logging back in is required.

We have been seeing some isolated oddities from the Google api over the last couple of weeks (such as spam messages being counted in the inbox #921) so I wonder if it could be related to this somehow.

It's probably worth trying to remove the Wavebox authentication from your Google account and then re-adding it. This might clear out any issue...
* In Wavebox, right click on the account and go to `Account Settings`
* Under the `Credentials` section, remove the Google Credential
* In your browser head to your Google Account/Apps with access (https://myaccount.google.com/permissions)
* Make sure you signed into the same account you removed the credential from in Wavebox
* Locate the Wavebox entry, click on it and then click remove access.
* Depending on if you signed into Wavebox with that account, there may be a second entry. Do the same with this.
* Back in the Wavebox app sign back into the account

See if that makes any difference. If it doesn't,
* Are these personal (e.g. @gmail.com) or corporate (e.g. @mycompany.com) accounts or both?
* How are you connected to the network? Home connection, work connection, vpn, proxy server etc?

**Comment by bmurphy1976** [comment]
3 personal, 1 corporate.  No proxies or anything like that.  Happens on both our work LAN/Wifi and home Wifi.  I'll try resetting the accounts next time it happens.

**Comment by bmurphy1976** [comment]
Well, I haven't had this happen in a couple weeks now.  No sense keeping it open.

**Comment by bmurphy1976** [comment]
Unfortunately this has started happening again.  I removed all my accounts and reinstalled them (no duplicates, just a single entry for each separate gmail account) and I'm still having the issue.  It's happening multiple times a day, and ever worse, this time around Google is sending me authentication alerts whenever I reauthenticate one of my accounts which didn't happen previously.

<img width="1253" alt="Screen Shot 2019-04-14 at 2 12 13 PM" src="https://user-images.githubusercontent.com/270488/56097891-b631eb00-5ebf-11e9-86a7-264101e15604.png">

**Comment by Thomas101** [comment]
@bmurphy1976 which version of the app are you using now?

It might also be worth giving the beta version ([4.9.4](https://github.com/wavebox/waveboxapp/releases/download/v4.9.4/Wavebox_4_9_4_osx.dmg)) a try, we've changed the way authentication works in that version which means you might not see this behaviour

**Comment by bmurphy1976** [comment]
Currently using 4.93.  It happened again this morning.  I'll try the beta version and see what happens.

**Comment by bmurphy1976** [comment]
Looks promising.  I was "unauthenticated" when I closed 4.9.3.  I was "authenticated" when I opened the 4.9.4 version.  I didn't have to do the re-authentication song and dance.  I'll give it a couple days and see what happens.

**Comment by bmurphy1976** [comment]
Seems to be working great with the new builds.  Thanks!!

**Comment by jeremymoore** [comment]
I have been having the same issues and wanted to also confirm that downloading the beta worked out great! Although the application state was still showing unauthenticated when I opened after installing the update, simply clicking the "authenticate" button pushed me through without needing to reauthenticate. So glad this is fixed!!! 🎉
