### ISSUE TITLE
Intercom Notifications Not Working

### ISSUE THREAD

**Issue by lots0logs** [wavebox/waveboxapp#938]
* Wavebox Version: 4.7.2
* Operating System & Version: Arch Linux w/ Cinnamon Desktop
* (Linux only) Install method: [AUR package](https://aur.archlinux.org/packages/wavebox-bin)
* Account type (if applicable): N/A

**Expected & actual behavior**
Expect to see badge on Intercom icon with number of unread notifications.

**Steps to reproduce**
Simply add Intercom, log in and wait until you have a notification.

**Is the bug persistent or intermittent?**
Its persistent.

**Comment by lots0logs** [comment]
@Thomas101 I tried creating a user script for this but it seems my calls to `wavebox.badge.setCount()` and `wavebox.badge.setHasUnreadActivity()` are being ignored. No errors are thrown. Any ideas?

**Comment by Thomas101** [comment]
Hey, it looks good. I've not been able to get the `hasActivity()` or `getUnreadCount()` to show anything other than `false` and `0` here - probably because I haven't setup the account properly.

I'm guessing you tried adding this into the Intercom app? The client api is normally opt-in with the `Any Website` accounts only. Try the following...

* Add a new account and pick `Any website` from the login screen
* Use `https://app.intercom.io` when prompted for a url then sign in
* Right click on the account and go to `Account Settings`. Under the `Account` section enable `Wavebox API`

If you bring up the dev tools via <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> you should be able to paste in `wavebox.badge.setCount(10)` or `wavebox.badge.setHasUnreadActivity(true)` and see an immediate effect.

**Comment by lots0logs** [comment]
That works. I had to make a small modification to the script. Here is the working copy:
```
function hasActivity() {
  return null !== document.querySelector('.left-nav__unread:not(.o__hidden)');
}

function getUnreadCount() {
  const unreads = Array.from(document.querySelectorAll('.left-nav__unread:not(.o__hidden)'));
  return unreads.reduce((total, node) => total + Number(node.textContent.trim()), 0);
}

const observer = new MutationObserver(mutations => {
  const count = getUnreadCount();

  wavebox.badge.setCount(count);
  
  if (! count) {
    wavebox.badge.setHasUnreadActivity(hasActivity());
  }
});

const ready_observer = new MutationObserver(mutations => {
  const left_nav = document.querySelector('.left-nav');

  if (null === left_nav) {
    return;
  }

  ready_observer.disconnect();
 
  observer.observe(left_nav, { childList: true, subtree: true, attributes: true, characterData: true });
});

ready_observer.observe(document.body, { childList: true, subtree: true });
```

**Comment by Thomas101** [comment]
That's awesome! If you want I can add this into the standard Intercom app. Just open a PR on https://github.com/wavebox/wavebox-user-scripts and I'll get the app to pull it across 😊. Also if you want some stickers, just send [support](https://wavebox.io/support) an email and we'll send some out to you 😊
