### ISSUE TITLE
Happy 100th Anniversary release

### ISSUE THREAD

**Issue by reatlat** [wavebox/waveboxapp#944]
<img width="1037" alt="waveboxapp at v4 7 3 2019-02-20 23-11-24" src="https://user-images.githubusercontent.com/9933516/53128401-0bf3b200-3565-11e9-9916-be45150821be.png">

Just want ta say TY for Wavebox team, GitHub community, and for all who made WaveBox better and better each release!

**Comment by Thomas101** [comment]
@reatlat thank you so much! It means a lot to us to hear nice things, we love what we do with Wavebox and love making it the best we can!


I have to admit, in all of our busyness and working to get release 101 ready we completely missed that we went treble figures with the last release! It’s kind of inspired me to work out some other interesting Wavebox related stats this morning…

👍 In that 100 releases, we’ve had 49 stable releases starting at version 3.1.0.
📅 That’s an average of one release a week and a stable every fortnight (although in all fairness stable releases are normally clumped together!)
👍 Each release has an average of 16 commits and each stable has an average of 33
😮 We’ve added 1597 commits since the first release
👋 The most popular days of the week for adding code is a Wednesday & Friday (Friday is noodles day)
👍 Wavebox has seen 13 versions of Chromium
🥚 So far there’s been 1 easter egg and 4 different types of official Wavebox stickers
🖥️ We've accumilated 18 different test boxes of different ilks and flavours, none of them have a floppy disk drive
☕ We guestimate it's taken us 5000 cups of coffee and we've gone through 2 new apple keyboards
🖊️We've dried out 46 dry wipe pens but are still on our first reem of 500 sheets of paper 🌳
🤓 Since starting Wavebox, one of us has moved from macOS to Linux full time and the rest of use macOS & Windows

Here’s to the next 100 releases 😊

**Comment by Thomas101** [comment]
And then 100 was 101 with the next beta 😄

**Comment by reatlat** [comment]
@Thomas101 find **Easter egg** !!!
Challenge accepted 🙃

**Comment by Thomas101** [comment]
Hint: it's not in the latest version of the codebase ;-)

**Comment by Thomas101** [comment]
Now that we're on release 104 it's probably time to close this off. Thanks for the celebration :)

![](https://media.giphy.com/media/1zkMdevx4zPh7Oft1a/giphy.gif)
