### ISSUE TITLE
copying a URL

### ISSUE THREAD

**Issue by CheechGe** [wavebox/waveboxapp#963]
* Wavebox Version: [e.g. 3.0.0] 4.7.11 Beta
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
Windows 10
**Is your feature request related to a problem? Please describe.**
Some information about what the problem is.
There are several earlier requests to add the ability to copy a URL which apparently have been implemented.  But if these were implemented they don't work on the News site (bbc.com) that is a 
 defined service in my Wavebox
**Is your feature request related to an account type?**
For example, a Gmail account or Trello account.
News site

**Describe the solution you'd like**
Information about what you want to happen or like to see.
Add or fix the ability to copy a URL from a news site

**Additional info**
Any other information or screenshots that might help us.
![wb_01](https://user-images.githubusercontent.com/3653639/53827404-ff9a2c80-3f48-11e9-9534-7ee1e8bd9758.png)

**Comment by nmat** [comment]
Hello,

This seems to be fixed in the next and upcoming release (tested here)

1. This has been added in: https://github.com/wavebox/waveboxapp/issues/936 where you can right click and then copy etc from any url. 

![image](https://user-images.githubusercontent.com/383031/53836054-47dc3d80-3f8f-11e9-9f65-8347db185689.png)

2. If you want to go around it......right click on the content and select "Copy Current URL" or set the keybinding for the value:

![image](https://user-images.githubusercontent.com/383031/53835966-0481cf00-3f8f-11e9-8e49-e25e969460a2.png)

Then you can when in that tab hit for example: Ctrl+Shift+C to get the current url.

Until the release of where: https://github.com/wavebox/waveboxapp/issues/936 is released then I would suggest the last few workarounds.

**Comment by Thomas101** [comment]
As @nmat said this is coming out in the next release. You'll be able to click into the url bar, copy, paste edit etc. In the current version, there's also `Copy Current URL` in the right-click menu in-page...
![screenshot 2019-03-06 at 08 34 55](https://user-images.githubusercontent.com/103586/53867015-ce723880-3fea-11e9-9884-6147d22d85ec.png)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.7.12. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by CheechGe** [comment]
Hi Thomas:

Works perfectly!  Thank you.  Please close the ticket.

Regards,

Frank
