### ISSUE TITLE
Wrong access rules for repo.list and crash non sudo apt

### ISSUE THREAD

**Issue by nipnull** [wavebox/waveboxapp#983]
Wavebox Version: 4.8.3 (deb)
Operating System & Version: Debian Stable
Install method: Apt-Repo

Behavior: I expect that adding repo.list by instructions from https://wavebox.io/download/ with Apt don't crash non sudo using apt.

Reproduce: Add repo as in manual on site and execute "aptitude search something" or "apt-cache search something".

PoC: "$ apt-cache search wavebox
E: Opening /etc/apt/sources.list.d/repo.list - ifstream::ifstream (13: Permission denied)
E: The list of sources could not be read."

It's persistent bug.

It could be fixed by adding "sudo chmod a+r /etc/apt/sources.list.d/repo.list" in manual.

**Comment by nmat** [comment]
This seems to be more of a bug in the system rather then how wavebox behaves.

The errors you are showing is coming from the system because of any addition to the /etc/apt/ should be used with sudo unless you change the tree of permissions.

you would most likely get errors when trying to read the file using any other application also because as you mention to have to change the permissions with a+r.

I checked the instructions:
sudo wget -qO - https://wavebox.io/dl/client/repo/archive.key | sudo apt-key add -
echo "deb https://wavebox.io/dl/client/repo/ x86_64/" | sudo tee --append /etc/apt/sources.list.d/repo.list
sudo apt update
sudo apt install wavebox

And this is common practice to do the addition of sources. And so I can't see that this is in anyway related to be a bug in wavebox

**Comment by nmat** [comment]
I tested the:

echo "deb https://wavebox.io/dl/client/repo/ x86_64/" | sudo tee --append /etc/apt/sources.list.d/repo.list

and this made no problems with me running apt as non sudo user

**Comment by nipnull** [comment]
@nmat, it maybe connected with umask and other default settings in different distros.
So i think that additional check for giving ro access for all users will not be redundant.

Bad PoC on debian stable:
$ ls -ahl /etc/apt/sources.list.d                 
total 20K
drwxr-xr-x 2 root root 4.0K Mar 12 06:03 .
drwxr-xr-x 6 root root 4.0K Mar 12 06:03 ..
-rw-r----- 1 root root   47 Mar 12 06:03 repo.list
etc

**Comment by nmat** [comment]
I just did a completely new install of debian 9 stable on a virtual machine here.

Installed sudo and added my user to the sudo group.

Followed instructions on website and this is what I get:

![image](https://user-images.githubusercontent.com/383031/54492654-d07ca700-48c8-11e9-82b8-4e5e4f404ab2.png)

**Comment by Thomas101** [comment]
I see the same as @nmat with a fresh install, and using the instructions on the download page, the permissions are `-rw-r--r--` and `apt-cache search wavebox` works as expected from a non-sudo user.

As this is the default configuration, we don't want to start suggesting users do things like re-writing file permissions when not strictly needed.
